### ISSUE TITLE
Official Star Fox 2 SNES Mini dump doesn't boot in ares

### ISSUE THREAD

**Issue by RokkumanX** [ares-emulator/ares#10]
Hi

Every game in my Super Famicom/Super Nintendo collection boots properly except Star Fox 2 (USA)

ares doesn't generate an error message but instead refuses to boot the ROM and changes back to unloaded state.

It was a long time I used the stand alone version of higan but I remember the game used to work fine there, at least the game works with the Libretro port of higan as of today.

**Comment by FitzRoyX** [comment]
Hmm, no problems here. This is what the manifest viewer says once loaded:

```
game
  name:     Star Fox 2 (USA)(1.0)
  title:    Star Fox 2 (USA)(1.0)
  label:    STARFOX2
  region:   USA
  revision: 1.0
  board:    GSU-RAM
    memory
      type: ROM
      size: 0x100000
      content: Program
    memory
      type: RAM
      size: 0x10000
      content: Save
    oscillator
      frequency: 21440000
```

Unfortunately, I get drops to 52fps on my 4ghz cpu for superfx games, hehe

**Comment by RokkumanX** [comment]
Whoa......FitzRoyX commenting in this issue, that's legendary!!!!!!

Thanks for chiming in but how the hell do you manage to run this game buddy?!?

According to `higan-emu/ares/blob/master/mia/Database/Super Famicom.bml` there is no Star Fox 2 (USA)(1.0) entry.

I have downloaded the latest nightly of ares (a2847224866d617770622a1c5e1f400fdf8b63a0) and I can't get squat to show, as soon as I load the game it reverts back to unloaded.

You got a special build or something?

**Comment by FitzRoyX** [comment]
The game doesn't need a db entry to run in Ares, so I wouldn't attempt to give it one if I were you. Delete the entry and it should work. If you're trying to run the game as a game folder with a manifest inside it, don't do that either.

The Super Famicom.bml database only contains games that Near verified. If a game loaded that isn't in that db, Ares will scan the rom data and construct a best guess mapper that almost always works.

I can tell you that the db entry you tried to give it has some wrong values. The 0x200000 value for the ROM size is wrong. It should be 0x100000. "label" should be "title". Also verify that your rom is what it says it is. It should be 1MB and have a hash of that starts with e134f. You can use a tool like hashcalc to find the sha256.

**Comment by RokkumanX** [comment]
OK here's what we're gonna do, scratch the entries I posted above and forget about them completely because they are not from **ares** but from a three year old version of higan which I myself tailor made.

Here is the steps for me to reproduce the actual problem which we are here for:

1. Download latest nightly of **ares** and nothing else.
2. Extract said download to a folder
3. Configurate **ares** to my liking
4. Restart the emulator and attempt to start the game (which by the way was verified over 3 years ago with HashCalc, and yes a tool I'm very much familiar with and that I use on a daily basis)
5. The emulator refuses to load my copy of the game with following checksums, **crc32:** 87653732, **md5:** 7d66769f53cb3fb7f5c73044876db240, **sha1:** 1135a2a6cb786ac7523e81dd553dc81aaa266f51, **sha256:** e134f20f6ee7d422d06faea6b1ae1e4101d1d0a200a0571d715d1cf23d959e8c which by the way is verified by [dat-o-matic](https://webcache.googleusercontent.com/search?q=cache:2Gq_PyScnV4J:https://datomatic.nointro.org/index.php%3Fpage%3Dshow_record%26s%3D49%26n%3D3683+&cd=3&hl=sv&ct=clnk&gl=se)

And there you have it, if you don't still believe me here is a couple of images:

![proof-ares](https://user-images.githubusercontent.com/85066613/125559538-46d25984-f843-4a48-bea4-f015625cc6b9.png)

![proof-ares-2](https://user-images.githubusercontent.com/85066613/125559562-c0f83b5f-ebf7-40ee-8b74-31442db6e815.png)

See the difference?

**Comment by RokkumanX** [comment]
You can't load Star Fox 2 with cli-commands like the other games for some weird reason.

I had to load Star Fox 2 and only Star Fox 2 from within the emulator, why is some things so complicated?!?

**Comment by RokkumanX** [comment]
Ignore this, everything works fine now, nothing to see here.....
