### ISSUE TITLE
[MD] Regression: All Mega Drive games is running at 44 FPS rather than 60 if run-ahead is on

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#103]
As of https://github.com/higan-emu/ares/commit/2380e62c79708cc1e284fc010ed7e7cd94ef4983 Mega Drive games now is funning at the wrong speed if run-ahead turn on.
This also affects Mega CD and 32X.
The best option, for now, seems to turn run-ahead off for all the Mega Drive based systems.

Tested within a Windows 10 x64 with ares https://github.com/higan-emu/ares/commit/2380e62c79708cc1e284fc010ed7e7cd94ef4983

**Comment by sards3** [comment]
This probably just means your CPU isn't fast enough.

**Comment by LukeUsher** [comment]
yeah, not so much a regression as much as the system requirements increasing, there's nothing we can do about this in the near future without breaking some games/reducing compatibility

**Comment by LukeUsher** [comment]
Closing as this is not a regression, just a performance/system requirements increase.
