### ISSUE TITLE
[MD] Demons of Asteborg - Graphical errors in the opening text

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#104]
This is a freshly released Mega Drive/Genesis game.
The issue happens is reportedly to happens in both the Demo version and the complete version (but I just have the demo version to test it now).
You can get a free demo ROM from the developer's website.
https://www.demonsofasteborg.com/

The full game as a ROM it's also selling there too.

There's are some screens of the game in ares with corrupted graphics in most recent version of ares (v123 dev-https://github.com/higan-emu/ares/commit/2380e62c79708cc1e284fc010ed7e7cd94ef4983)
![image](https://user-images.githubusercontent.com/12163923/130889191-b4dd41d2-9174-4b7b-ad6a-47db6f006d35.png)
![image](https://user-images.githubusercontent.com/12163923/130891525-7a31f2af-9e5c-4ee8-b09d-0df5369341b7.png)
![image](https://user-images.githubusercontent.com/12163923/130889283-6429ccb8-1823-42d2-bd7f-17708a27f9d3.png)
![image](https://user-images.githubusercontent.com/12163923/130891543-51a4949a-43ab-422f-ac96-0450aeccaf6f.png)

EDIT: This is the same game tested in MAME as a reference.
[video](https://youtu.be/cfHLxtPSzsk)

**Comment by Shideravan** [comment]
A similar graphical error also happens in Comix Zone
![image](https://user-images.githubusercontent.com/12163923/131066597-c06740fd-d8fb-4fab-82d3-112697b664aa.png)

**Comment by Shideravan** [comment]
The same with Mega Man: The Wily Wars
![image](https://user-images.githubusercontent.com/12163923/131070584-61c8ec0f-042e-4f04-91fa-efa06a198144.png)
![image](https://user-images.githubusercontent.com/12163923/131070622-5fd74571-3d65-4e64-b4a4-f3c710df9e7a.png)
![image](https://user-images.githubusercontent.com/12163923/131070813-c8ad554d-7a1e-40da-b3f3-1246edd2f371.png)

**Comment by TascoDLX** [comment]
Confirmed to be a bug in DMA fill op: first byte written is incorrect. I should be able to track it down.

**Comment by Shideravan** [comment]
Fixed with https://github.com/higan-emu/ares/pull/110
