### ISSUE TITLE
question: pc2 and ws button position

### ISSUE THREAD

**Issue by soundsnow** [ares-emulator/ares#1081]
I want to submit code for StoicGoose,NitroSwan and libretro. add pocket challenge v2 support for them. I want to know the button position and button name of pc2 and the corresponding button position and button name of ws
I've done a lot of button testing and I think my test result might be wrong. that's why i'm here to ask you

**Comment by jeffythedragonslayer** [comment]
I don't know how to read your table.  What the rows supposed to represent, and why are there empty cells and empty column names?

**Comment by soundsnow** [comment]
this is my test result,it might be incorrect
I don't know some button names

left| |hand|right| |hand
:---:|:---:|:---:|:---:|:---:|:---:
| | |esc:x3|voice view:x1| | |
| |up:b| | | |pc2?:y1|
|pc2?:x4| |pc2?:x4| |circle:y3| |
| |down:a| |pc2?:y4| | |

![image64](https://user-images.githubusercontent.com/109885044/189128409-80e8cf4b-6dd7-4161-8189-80882337956e.png)
![55416659-e22c-45d5-9f69-bb55f93bf20e](https://user-images.githubusercontent.com/109885044/189128474-aa8df2e7-9b76-4d4a-b5d5-2a11729fc26b.png)

**Comment by Screwtapello** [comment]
Here's the code where ares converts the user's mappings into data that the emulated software can see:

https://github.com/ares-emulator/ares/blob/acff6a93adbe823ffd7f803edc4340ed480cd517/ares/ws/cpu/keypad.cpp

It's a little complicated by the fact that ares silently remaps the D-pads when the emulated device is rotated vertically, but if we assume that "horizontal" is the natural orientation, we get:

| WonderSwan    | PocketChallenge V2 |
| ------------- | ------------------ |
| y1            | clear              |
| y2            | (always held)      |
| y3            | circle             |
| y4            | pass               |
| x1            | view               |
| x2            | (always held)      |
| x3            | escape             |
| x4            | rightLatch         |
| (unconnected) | leftLatch          |
| start         | (always held)      |
| a             | down               |
| b             | up                 |

"unconnected" means this bit in the control pad register is not wired to a physical button, so it's always 0 and cannot be pressed.

"always held" means this bit in the control pad register is not wired to a physical button, it's always 1 and cannot be un-pressed.

**Comment by soundsnow** [comment]
thank you

**Comment by soundsnow** [comment]
> Here's the code where ares converts the user's mappings into data that the emulated software can see:
> 
> https://github.com/ares-emulator/ares/blob/acff6a93adbe823ffd7f803edc4340ed480cd517/ares/ws/cpu/keypad.cpp
> 
> It's a little complicated by the fact that ares silently remaps the D-pads when the emulated device is rotated vertically, but if we assume that "horizontal" is the natural orientation, we get:
> WonderSwan 	PocketChallenge V2
> y1 	clear
> y2 	(always held)
> y3 	circle
> y4 	pass
> x1 	view
> x2 	(always held)
> x3 	escape
> x4 	rightLatch
> (unconnected) 	leftLatch
> start 	(always held)
> a 	down
> b 	up
> 
> "unconnected" means this bit in the control pad register is not wired to a physical button, so it's always 0 and cannot be pressed.
> 
> "always held" means this bit in the control pad register is not wired to a physical button, it's always 1 and cannot be un-pressed.

pass and clear
Which is on the left?  which one is on the right?
is pass->circle->clear or clear->circle->pass?

**Comment by Screwtapello** [comment]
I assume the button that shows an arrow going around something is "pass", so "pass→circle→clear".
