### ISSUE TITLE
[MD] Super Hydlide (J): Doesn't registering the player

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#112]
You can normally start the game by selecting the following options (select every option with C button):
* 3rd option (create)
* write any name and choose the last option (end)
* In this screen you choose one of 4 classes. Choose any.
* Will show the status and confirm. Press C in the first option (yes)
* The first option is "start" to start the game. But will appear a message "not registered". Even after registering yourself.
![image](https://user-images.githubusercontent.com/12163923/131074108-9a9a95ae-26aa-4f30-8ae0-46d430a1e6e7.png)

The issue only happens in Japanese version. And it doesn't create a save file, then probably the issue is save related.

**Comment by LukeUsher** [comment]
fixed by #267
