### ISSUE TITLE
[N64] Sound different when played in 50 Hz.

### ISSUE THREAD

**Issue by randomsomeone69** [ares-emulator/ares#1120]
**Describe the bug**
Different pitch and speed when playing a European game (50 Hz)

**To Reproduce**
1. Select a European game
2. Put the sound on
3. Listen how the sound is off 

**Expected behavior**
A clear sound like an Japanese/American game.

**Additional context**
The sound is perfect when played on a real European N64.

**Comment by Kawa-oneechan** [comment]
Sound's off because you're playing 50 Hz sounds at 60 Hz, I'd wager. If nothing else, this option may help:
![image](https://github.com/ares-emulator/ares/assets/12450280/8fec32ff-88b7-46a9-b2de-0d469fa1b2c9)

**Comment by randomsomeone69** [comment]
I've set it up into Europe, but the pitch is still off and the speed too. This didn't help.
