### ISSUE TITLE
[PS] Fun! Fun! Pingu - Youkoso! Nankyoku e (Japan): Black screen when starting a new game

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#115]
Also, the configuration menu has a corrupted music

**Comment by remutro** [comment]
While it is great that someone is testing the PS core (no one is really testing it internally or working on it as far as I know), I'm not sure it is going to be worthwhile filling up Github issues with PlayStation issues at this time (it's literally a 1 star core and the library is massive). Perhaps it would be better for now to open a PlayStation Compatibility issue list and list problematic games. 

I will default to @LukeUsher 's opinion on this one. I just don't want to see hundreds of PS issues drown out other cores that may only have a handful of issues left to resolve (and Github doesn't really help here).

**Comment by Shideravan** [comment]
You're right.
I think that open a single issue to receive all the PlayStation compatibility issues is a better idea until the core becomes more mature to avoid a potential flood. I'll close this.

**Comment by Shideravan** [comment]
https://github.com/higan-emu/ares/issues/150
