### ISSUE TITLE
[MD] Landstalker: Garbage just above the text boxes

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#117]
This line is shown incorrectly every time a text box appears
![image](https://user-images.githubusercontent.com/12163923/131152195-a3b446cc-0266-4a3e-97de-3efaee0cc945.png)

**Comment by rasky** [comment]
Seems fixed now? Or I don't understand the bug

**Comment by BenjaminSiskoo** [comment]
I saw this kind of artefact but I don't remebmer the name of the game.

![landstalker](https://user-images.githubusercontent.com/12481242/154712207-f9c20401-a2c1-4b2d-9eb2-db65698f0966.gif)

**Comment by BiZkViT96** [comment]
Bug is still there

ares nightly 2022-09-13

**Comment by mickagame** [comment]
I'm waiting the fix for this bug. I would like to play this game on ares :-)

**Comment by Kawa-oneechan** [comment]
Why _not_ play it? What even are we talking about here, a single line of graphics that jutters a bit as a Mega Drive game tries to switch between two graphics sets mid-frame in order to display a text box? Seems playable enough, but maybe that's just me.

**Comment by Shideravan** [comment]
Yes, I reported because ares strives for accuracy, then every small issue needs investigation and fix.
But the game is playable enough if you just want to play it and can ignore this small issue ;-)

**Comment by Kawa-oneechan** [comment]
> ares strives for accuracy

And in this now almost two years old issue, nobody reported on what the game actually shows on real hardware, so as far as I'm concerned it could well already _be_ accurate as far as this issue is concerned 🤷‍♀️

**Comment by Shideravan** [comment]
> > ares strives for accuracy
> 
> And in this now almost two years old issue, nobody reported on what the game actually shows on real hardware, so as far as I'm concerned it could well already _be_ accurate as far as this issue is concerned 🤷‍♀️

This issue _doesn't_ happens in the real console.
https://www.youtube.com/watch?v=w0NzhHZV3vk

Direct real hardware console capture using a Elgato HD Pro 60
