### ISSUE TITLE
[NGPC] Gals' Fighters: Resets the system when certain moves are performed in fights

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#118]
The easy way to reproduce seems to performs/spam May's Sayochidori (down, back + B) in any fight. There's also some moves that have the same issue. Maybe they're trying to access an incorrect memory position?

Ps.: Just to be sure, I already make sure that the power button isn't assigned to anything.
![image](https://user-images.githubusercontent.com/12163923/131154477-5c191ca0-d392-4a7f-ac03-9864f64f1674.png)

**Comment by invertego** [comment]
Fixed by #121. Thanks for the report!
