### ISSUE TITLE
[MD] Férias Frustradas do Pica-Pau: Graphical errors in the diver level

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#123]
![image](https://user-images.githubusercontent.com/12163923/131220287-e0bfa49c-fa2f-4b32-8233-6ee36e1c5744.png)

This is like it had to be:
https://youtu.be/TWzSCK8HICw?t=1072

Version: 2c970ca
Windows 10 x64

There's a save state for the level attached: [Ferias Frustradas do Pica Pau (Brazil).zip](https://github.com/higan-emu/ares/files/7070800/Ferias.Frustradas.do.Pica.Pau.Brazil.zip)

**Comment by FitzRoyX** [comment]
@Shideravan please verify that this doesn't happen on the latest build. I believe it was fixed some time ago.

**Comment by FitzRoyX** [comment]
I've confirmed this is fixed by using the level skip code
