### ISSUE TITLE
[N64] AI Shougi 3 (J): No voice clips

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#124]
No sound and no voice clips in AI Shougi 3 (J) with any audio driver.
ares e6948d2
Windows 10 x64

**Comment by remutro** [comment]
AI Shougi 3 doesn't have background music, even during the intro. It's admittedly weird but that is correct behavior. There are proper sound effects and commentary while in-game. 

See here: https://www.youtube.com/watch?v=SdFcW-1bNlU

If you want to repurpose this issue then you can change the game to "Twisted Edge - Extreme Snowboarding [King Hill 64 (J)]". This game in all regions has zero sound anywhere in the game.

**Comment by Shideravan** [comment]
> AI Shougi 3 doesn't have background music, even during the intro. It's admittedly weird but that is correct behavior. There are proper sound effects and commentary while in-game.
> 
> See here: https://www.youtube.com/watch?v=SdFcW-1bNlU
> 
> If you want to repurpose this issue then you can change the game to "Twisted Edge - Extreme Snowboarding [King Hill 64 (J)]". This game in all regions has zero sound anywhere in the game.

I'm not talking about intro music. the game hasn't even the voice clips in-game in ares

**Comment by remutro** [comment]
There is something different between our systems then (or the ROM). Windows 10, using the WASAPI sound driver. I hear all sound effects as well as all commentary when in-game.

**Comment by Shideravan** [comment]
Probably it's related with realtek audio driver audio issues with bsnes/higan/ares. The games runs fine with the same realtek audio driver in other emulators (eg: mupen64plus)

**Comment by remutro** [comment]
I also have Realtek Audio. I'm not using their driver though because I had some issues with it (not related to emulation). So I'm just using the Microsoft provided driver, version: 10.0.19041.264

**Comment by Shideravan** [comment]
> I also have Realtek Audio. I'm not using their driver though because I had some issues with it (not related to emulation). So I'm just using the Microsoft provided driver, version: 10.0.19041.264

Unfortunately the audio quality from my desktop using default Microsoft driver drops and is a pain to maintain windows not chasing to latest realtek driver everytime.
But I'll check asap. Maybe #155 is also related to.

**Comment by LukeUsher** [comment]
Any updates on this?

**Comment by kev4cards** [comment]
I have checked this against current master. My experience is identical to remutro's. Therefore, should this be closed?
