### ISSUE TITLE
[MD] Duke Nukem 3D: Black screen (doesn't boot)

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#133]
ares e6948d2
Windows 10 x64

**Comment by BiZkViT96** [comment]
Bug report is not relevant. The game works fine as far as I can tell, I compared it against BlastEm.

![2022-02-25 19_55_30-Duke Nukem 3D (Brazil)](https://user-images.githubusercontent.com/88586431/155719242-76ff390d-48f5-455e-8696-fe20d89b8678.png)

Duke Nukem 3D (Brazil)
SHA1 a4663f2b96787a92db604a92491fa27e2b5ced9e

Tested on ares nightly 2022-02-23
