### ISSUE TITLE
[64DD] Few freezes occur when playing games.

### ISSUE THREAD

**Issue by randomsomeone69** [ares-emulator/ares#1346]
**Describe the bug**
During gameplay of severals games in the Nintendo 64DD, sometimes, the game will freeze for no reason for a few seconds, then go back to normal

**To Reproduce**
1. Load up a 64DD game. For my tests, it occured on Kyojin no Doshin and Kyojin no Doshin - Kaihou Sensen Chibikko Chikko Daishuugou

**Expected behavior**
A smooth gameplay with no freezing occuring.

**Screenshots**
[2023-12-14 21-52-28.zip](https://github.com/ares-emulator/ares/files/13689894/2023-12-14.21-52-28.zip)
Full session recording of the issue. (I'd had to compress the video for size issues. However, I kept it as clearly as I could.)

**Additional context**
I have a midly stong PC (Intel Core i5-10400F + nVidia GeForce 1050 Ti) and I've changed from OpenGL to Direct3D 9 and it kept freezing randomly for shorts periods of time. So I don't think for the hardware issue.

**Comment by remutro** [comment]
Does this disappear if you go to Settings > Options, and disable "Auto-Save Memory Periodically"?

If underlying storage isn't fast enough, this can create a brief pause with this option enabled. 

And does your system maintain a steady 60 VPS the whole time? The N64/DD core can be quite demanding at times. If unable to maintain a steady 60 VPS then interruptions are expected.

**Comment by randomsomeone69** [comment]
It dissapears when I uncheck the "Autosave Memory Periodically". No more stutters. Always 60 VPS.

Thanks for your time.
