### ISSUE TITLE
[N64] Olympic Hockey Nagano '98: Hangs in "Player 2 Rumble pak not supported" (even when Player 2 isn't even connected)

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#138]
Even when the only controller connected is Player 1. But the game hangs in the beginning in this screen.
![image](https://user-images.githubusercontent.com/12163923/131284688-986c7e27-776d-4b8b-bab3-83a73098b811.png)

**Comment by remutro** [comment]
I remember running into this when I tested this game. Assigning L + R buttons to controller 2 does allow you to move past this screen and the game is playable (as stated previously, controllers 2 - 4 always have a rumble pak attached to them currently in ares and this game doesn't support rumble). However if you disable the controllers in the GUI it shouldn't be leaving them connected. I plan to look at this a little more closely, we may have forgotten to wire up the disconnect. 

Edit to add: The input screen doesn't really have an option for "nothing". Looks like a gamepad is always assigned to a port.

**Comment by Shideravan** [comment]
A similar image appears in Wayne 3D Hockey, but I think that controller pak issues are caused by only partial implementation.
![image](https://user-images.githubusercontent.com/12163923/131364661-27389fca-7827-4755-a29d-93d77c78c015.png)

> Edit to add: The input screen doesn't really have an option for "nothing". Looks like a gamepad is always assigned to a port.

Then this option really doesn't make any difference? I think this makes sense for this bug happening then
![image](https://user-images.githubusercontent.com/12163923/131365030-e0a0da6b-d0ce-42d0-ad8c-9eb783aedc3c.png)

**Comment by remutro** [comment]
If you go into the Settings > Input section, there is always a Gamepad assigned to the port and no way to say Nothing. A number of folks reviewed my findings and agreed that the "Nothing" option isn't currently wired up to anything, so it won't have any impact right now. Therefore the controller pak issue is expected given our current implementation. Ares currently has no support for a controller pak in controllers 2 - 4 (and even limited support in controller one based on my comment here:  https://github.com/higan-emu/ares/issues/125#issuecomment-908348697 ). So it is seeing a rumble pak assigned for player 2, not a controller pak and Wayne Gretzky's 3D Hockey does not have support for rumble. With no way to actually remove connected controllers currently, you would need to assign L + R buttons to controller 2 to bypass this message so you can play the game.

**Comment by remutro** [comment]
Errors about the wrong peripherals should be addressed as of pull request 156. You shouldn't see these warnings anymore.

**Comment by Shideravan** [comment]
Fixed with #156 
Thanks @remutro for the fix
