### ISSUE TITLE
SDL Detects All controllers as F360

### ISSUE THREAD

**Issue by RinMaru** [ares-emulator/ares#1380]
SDL supports way more controllers than Windows mode does the problem is SDL reads all controllers as the same controller (**mappings is always read as F360**). PS5, Xbox, Switch Pro are all seen as the same controller making it impossible for Ares to distinguish them apart for different layouts options. Windows will identify them as separate entities allowing you to map at least 3 different controllers. This issue was recent when changes were made to SDL on nightlys of 1.34 before 1.35. 

Windows 11/ RX 6700XT/ R5 5600X

Heres my settings file and is set up as follows-
Mappings 1- Switch Pro
Mappings 2- Xbox One
Mappings 3- Dualsense
[settings.zip](https://github.com/ares-emulator/ares/files/14076873/settings.zip)
All controllers are interchangeably read as the same in SDL making it impossible to make diff profiles.

**Comment by LukeUsher** [comment]
Would it be possible to retest with the latest commit (https://github.com/ares-emulator/ares/commit/3d10cd34d6beb803030d2270d9ff44f2814025dc)

**Comment by RinMaru** [comment]
> Would it be possible to retest with the latest commit ([3d10cd3](https://github.com/ares-emulator/ares/commit/3d10cd34d6beb803030d2270d9ff44f2814025dc))

Yes. will do

**Comment by RinMaru** [comment]
it fixes it Thank You ^^
