### ISSUE TITLE
N64: RDP freeze not implemented

### ISSUE THREAD

**Issue by jeltaqq** [ares-emulator/ares#14]
It have the benefit of timing Blast Corps and DK64.

**Comment by LukeUsher** [comment]
Could you be more specific? I'm not very familiar with the n64 hardware just yet, so firstly, what *is* RDP freeze, and more importantly, what evidence do you have that it would benefit these specific games?

**Comment by bigbass1997** [comment]
RDP freeze is a flag that can be set in the RDP command registers, specifically the `RDP CMD DMA Status` register at address `0x0410000C`. When set, it halts (freezes) the RDP clock completely, effectively disabling it. Clearing the flag will allow it to resume.

While Mazamars and I understand how this affects the RDP at the hardware level; supporting it breaks things even more. There are games besides Blast Corps and DK64 that attempt to set the flag, however, if the flag is handled as noted above, the games get stuck. The flag gets set, but then never cleared, as if the games are stuck waiting for something before clearing the flag. In such cases, completely ignoring the flag allows the games to work, seemingly correctly.

We (including Near and Dillon) know that ignoring the flag isn't accurate behavior. The flag and it's immediate effect are known, and implemented, but writes to set the flag are explicitly ignored. We are missing something. It may have something to do with incorrect timing of DMAs, where something, or multiple sometimes, are finishing too fast or too slow.

**Comment by LukeUsher** [comment]
Excellent write up, fully understand the situation, thanks!

**Comment by jeltaqq** [comment]
As evidence, I am the last piece of DK64 that you can present the other HLEd emulator.

> [+] Implemented task freeze (DK64 gets in game now!, intro works fine too, in game has core issues though) https://github.com/DaedalusX64/daedalus/commit/80de207

**Comment by jhlkek** [comment]
> We (including Near and Dillon) know that ignoring the flag isn't accurate behavior. The flag and it's immediate effect are known, and implemented, but writes to set the flag are explicitly ignored. We are missing something. It may have something to do with incorrect timing of DMAs, where something, or multiple sometimes, are finishing too fast or too slow.

... does this mean Near is alive?

**Comment by Screwtapello** [comment]
No, it just means bigbass1997 was in too much of a rush to write out "We N64 emulation authors, including myself and Dillon and previously Near...".

**Comment by Shideravan** [comment]
Now Donkey Kong 64 gets ingame, but there's some graphical issues similar of those in Blast Corps: some 3D objects are flickering. Probably related with RDP freeze.

**Comment by ChromiusMixin** [comment]
In case anyone is wondering where Donkey Kong 64 is currently at: 
Going ingame, but bad amounts of flashing due to no RDP Freeze as said above.

Game can softlock on a new file if "Story Skip" isn't set to "On" in the ingame settings menu.

Seizure warning for the video below. Shows the first 3 minutes of Donkey Kong 64 in Ares.
[https://www.youtube.com/watch?v=JXfmZJJT-0I](url)

**Comment by remutro** [comment]
RDP Freeze has been implemented as of ares v129 

Blast Corps plays well now, DK64 still has issues related to timing.
