### ISSUE TITLE
[N64] CPU opecode Test LL LLD SC SCD fails

### ISSUE THREAD

**Issue by jeltaqq** [ares-emulator/ares#140]
Fails this CPU test ROM.
Gauntlet Legends uses this opcode maybe never booted in Ares. 

https://github.com/PeterLemon/N64/tree/master/CPUTest/CPU/LOADSTORE/LL_LLD_SC_SCD

![ll_sc](https://user-images.githubusercontent.com/25340049/131308552-7424fef2-a499-4279-b60c-10d528468a86.png)

**Comment by remutro** [comment]
@LukeUsher - this can be closed as a result of pull request: https://github.com/ares-emulator/ares/pull/547

**Comment by remutro** [comment]
All tests pass:

![image](https://user-images.githubusercontent.com/84990500/180343580-8006b337-79f8-4d0a-9c2d-52c4cc976db7.png)
