### ISSUE TITLE
[N64] Turok - Dinosaur Hunter: Multiple issues

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#141]
At the beginning of the game, it does a "soft reset" after the Iguana logo and only will escapes this loop if you press any button.
In the game itself, the game behaves as pressing multiple buttons by itself. The player seems to be walking and knifing even without buttons being pressed. Also, the buttons pressed aren't registered anymore.
https://youtu.be/s1Zop3vqAFs

**Comment by remutro** [comment]
Confirmed, this is already a known issue.

**Comment by invertego** [comment]
Both issues should be fixed with #170 and #171
