### ISSUE TITLE
[N64] Wave Race - Shindou Edition: Freezes in N64 logo

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#142]
This one is a very interesting issue as this affects only the Shindou edition, not the default version of Wave Race.
![image](https://user-images.githubusercontent.com/12163923/131363680-aab8ff85-bca7-4c5b-a6a1-12cd1b39cf92.png)

**Comment by remutro** [comment]
@Shideravan - Now that invertigo's pull request has been merged, the Shindou edition of Wave Race 64 should play fine (and also enable rumble). Please test/close this issue when you get a chance. Thanks!

**Comment by Shideravan** [comment]
Fixed with #161
