### ISSUE TITLE
[N64] Nintendo 64 Compatibility List

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#143]
I tested every Nintendo 64 official release. If the region isn't defined, it means the North American NTSC version.
Also, note that I'm not evaluating speed or framerate (and by extension, audio speed) as we know this core it's still pretty new and as everybody knows, there are some optimizations that still need to be done. But also is worth noting how many titles are already playable in this emulation core and how impressive it is considering the N64 emulation solution until this date.
Also, this may serve as a reference and I plan to update this list as the core receives more updates.

Updated until **ares 127 dev https://github.com/ares-emulator/ares/commit/3aa1b3b7389dffd0aff4f432de62f0ec9e764c8b**

**No issues found** (apart of speed/framerate issues)**:**
---
- 007 - The World is Not Enough (It used to hang after some time playing, (I played for nearly a hour and didn't hang to me with ares da53c2b)
- 1080 Snowboarding
- 64 de Hakken!! Tamagotchi Minna de Tamagotchi World (J)
- 64 Oozumou (J)
- 64 Oozumou 2 (J)
- 64 Trump Collection (J)
- A Bug's Life
- Aerofighters Assault
- AeroGauge
- AI Shougi (J) (but no audio clips in my end - maybe it's related with realtek audio driver issues?): https://github.com/higan-emu/ares/issues/124
- All Star Baseball '99
- All Star Baseball 2000
- All Star Baseball 2001
- All Star Tennis '99
- Aidyn Chronicles: The First Mage
- Airboarder 64 (E)
- Armorines: Project S.W.A.R.M.
- Army Men: Air Combat
- Army Men: Sarge Heroes 1
- Army Men: Sarge Heroes 2
- Asteroids Hyper 64
- Automobili Lamborghini
- Bakuretsu Muteki Bangai-O
- Bakusou Jinsei 64 (J)
- Banjo-Kazooie
- Banjo-Tooie
- Bass Masters 2000
- Bass Rush (J)
- Bass Tsuri No. 1 (J)
- Batman Beyond
- Battletanxs 1
- Battletanxs Global Assault
- Battlezone: Rise of the Black Dogs
- Beetle Adventure Racing
- Big Mountain 2000
- Bio F.R.E.A.K.S.
- Blues Brothers 2000
- Body Harvest
- Bomberman 64
- Bomberman 64: Arcade Edition (J)
- Bomberman 64: The Second Attack
- Bomberman Hero
- Bottom of the 9th
- Brunswick Circuit Pro Bowling
- Buck Bumble
- Bust-A-Move '99
- Bust-A-Move 2: Arcade Edition
- California Speed
- Carmageddon 64
- Castlevania 64
- Castlevania: Legacy of Darkness
- Centre Court Tennis (E)
- Chameleon Twist 1
- Chameleon Twist 2
- Charlie Blast's Territory
- Chopper Attack
- Choro Q 64 II (J)
- Chou Kuukan Night Pro Yakyuu King (J)
- Chou Kuukan Night Pro Yakyuu King 2 (J)
- Clay Fighter 63 1/3
- Clay Fighter: Sculptor's Cut
- Command & Conquer 64
- Cruis'n Exotica
- Cruis'n USA
- Cruis'n World
- Custom Robo (J)
- Custom Robo V2 (J)
- CyberTiger
- Daikatana
- DDR - Disney Dancing Museum (J)
- Dark Rift
- Deadly Arts
- Densha de Go! 64 (J)
- Derby Stallion (J)
- Destruction Derby 64
- Dezaemon 3D (J)
- Diddy Kong Racing
- Disney's Donald Duck Goin' Quackers
- Disney's Tarzan
- Doom 64
- Doreamon (J)
- Doreamon 2 (J)
- Doreamon 3 (J)
- Doubutsu no Mori (Animal Crossing) (J)
- Dr. Mario 64
- Dual Heroes
- Duck Dodgers
- Duke Nukem 64
- Duke Nukem - Zer0 H0ur
- Earthworm Jim 3D
- ECW Hardcore Revolution
- Eikou no Saint Andrews (J)
- Elmo's Letter Adventure
- Elmo's Number Journey
- Excitebike 64
- Extreme-G 1
- Extreme-G XG2
- F-1 Pole Position 64
- F-1 World Grand Prix 1
- F-1 World Grand Prix 2 (E)
- F-Zero X
- F1 Racing Championship (Brazil)
- Famista 64 (J)
- FIFA 98
- FIFA 99
- Fighter's Destiny 1
- Fighter's Destiny 2
- Fighting Force 64
- Fire Electric Pen (J)
- Flying Dragon
- Forsaken 64
- Fox College Hoops
- Fushigi no Dungeon: Fuurai no Siren 2: Oni Shuurai! Siren Shiro! (J)
- Ganbare Goemon Mononoke Sugoruku
- Ganbare Nippon! Olympics 2000 (J)
- Getter Love!! Cho Renai Party Game (J)
- Gex 3
- Gex 64
- Glover
- Goemon's Great Adventure
- Golden Nugget 64
- Goldeneye 007
- GT 64 
- Hamster Monogatari (J)
- Hanafuda 64 (J)
- Harukanaru Augusta Masters 98 (J)
- Harvest Moon 64
- Heiwa Pachinko World 64 (J)
- Hercules: The Legendary Journeys
- Hexen
- Hey You Pikachu! (the game runs fine, but it's unplayable yet due to lack of VRU support)
- Hot Wheels Turbo Racing
- Hybrid Heaven
- Hydro Thunder (Used to hang at the start of the race. I cannot reproduce in most recent builds anymore)
- Ide Yousuke no Mahjong Juku (J)
- Iggy's Recking' Balls
- In-fisherman Bass Hunter 64
- Indiana Jones and the Infernal Machine
- Indy Racing 2000
- International Superstar Soccer '98
- International Superstar Soccer 2000
- International Superstar Soccer 64
- International Track & Field 2000
- J. League Dynamite Soccer 64 (J)
- J. League Eleven Beat 1997 (J)
- J. League Live 64 (J)
- J. League Tatics Soccer (J)
- Jeopardy
- Jeremy McGrath Supercross 2000
- Jikkyou G1 Stable (J)
- Jikkyou J.League Perfect Striker (J)
- Jikkyou J.League 1999 - Perfect Striker 2 (J)
- Jikkyou Powerful Pro Yakyuu - Basic Han 2001 (J)
- Jikkyou Powerful Pro Yakyuu 2000 (J)
- Jikkyou Powerful Pro Yakyuu 4 (J)
- Jikkyou Powerful Pro Yakyuu 5 (J)
- Jikkyou Powerful Pro Yakyuu 6 (J)
- Jinsei Game 64 (J)
- Ken Griffey Jr.'s Slugfest
- Killer Instinct Gold
- Kira to Kaiketsu! 64 (J)
- Kirby 64: The Crystal Shards
- Knife Edge: Nose Gunner (Too fast?)
- Knockout Kings 2000
- Kobe Bryant's NBA Courtside
- Kuiki Uhabi Suigou (J)
- Last Legion UX (J)
- LEGO Racers
- Legend of Zelda: Majora's Mask
- Legend of Zelda: Ocarina of Time
- Legend of Zelda: Ocarina of Time Master Quest (E)
- Lode Runner 3-D
- Mace: The Dark Age
- Madden Football 64
- Madden NFL '99
- Madden NFL 2000
- Madden NFL 2001 (Too fast in opening and in menus): https://github.com/higan-emu/ares/issues/130
- Madden NFL 2002
- Mahjong 64 (J)
- Mahjong Hourouki Classic (J)
- Mahjong Master (J)
- MLB Ken Griffey Jr. (Logos' graphics flickering)
- Mario Golf
- Mario Kart 64
- Mario no Photopie (J) (The game runs, but SmartMedia card isn' supported. Modded version to skip SmartMedia Cards runs): https://github.com/higan-emu/ares/issues/134
- Mario Party 2
- Mario Party 3
- Mario Tennis
- Mega Man 64
- Mia Hamm Soccer 64
- Michael Owens WLS 2000 (E)
- Micro Machines 64 Turbo
- Midway's Greatest Arcade Hits Volume 1
- Mike Piazza's Strike Zone
- Milo's Astro Lanes
- Mischief Makers
- Mission: Impossible
- Monaco Grand Prix
- Monopoly
- Morita Shogi 64 (J)
- Monster Truck Madness 64
- Mortal Kombat 4
- Mortal Kombat Mythologies: Sub Zero
- Mortal Kombat Trilogy
- MRC: Multi Racing Championship
- Ms. Pac-Man Maze Madness 
- Mystical Ninja: Starring Goemon
- Nagano Winter Olympics '98
- Namco Museum 64
- Nascar '99
- Nascar 2000
- NBA Courtside 2
- NBA Hang Time
- NBA In the Zone '98
- NBA In the Zone '99
- NBA In The Zone 2000
- NBA Jam '99
- NBA Jam 2000
- NBA Live '99
- NBA Live 2000
- NBA Showtime: NBA on NBC
- Neon Genesis Evangelion 64 (J)
- New Tetris
- NFL Blitz
- NFL Blitz Special Edition
- NFL Blitz 2000
- NFL Blitz 2001
- NFL Quarterback Club '98
- NFL Quarterback Club '99
- NFL Quarterback Club 2000
- NFL Quarterback Club 2001
- NHL '99
- NHL Blades of Steel '99
- NHL Breakaway '98
- NHL Breakaway '99
- Nightmare Creatures
- Nuclear Strike 64
- Nushi Tsuri 64 (J)
- Nushi Tsuri 64: Shiokaze Ninotte (J)
- Off-Road Challenge
- Ogre Battle 64: Person of Lordly Caliber
- Olympic Hockey '98
- Pachinko 365 Nichi
- Paper Mario
- Paperboy 64
- Parlor! Pro 64: Pachinko Jikki Simulation Game (J)
- PD Ultraman Battle Collection 64 (J)
- Penny Racers
- Perfect Dark
- PGA European Tour Golf
- Pilotwings 64
- Pocket Monsters Stadium (J)
- Pokemon Puzzle League
- Pokemon Snap
- Pokémon Stadium 1 (U) (Doesn't have the Transfer Pak support yet)
- Pokémon Stadium 2 (U) (Doesn't have the Transfer Pak support yet)
- Polaris SnoCross (Used to hang at the start of the race. I cannot reproduce in most recent builds anymore)
- Power League Baseball 64 (J)
- Power Rangers: Lightspeed Rescue
- Powerpuff Girls: Chemical X-Traction
- Premier Manager 64 (E) (Message: "Controller pak may be damaged" on start screen)
- Pro Mahjong Tsuwamono 64: Jansou Battle ni Chousen (J) (after "press start", choose the second option, "new game")
- Puyo Puyo Sun 64 (J)
- Puyo Puyo 4: Puyo Puyo Party (J)
- Quake
- Quake II
- Quest 64
- Rakuga Kids (E)
- Rally Challenge 2000 (Message: "the controller pak is not connected")
- Rampage: World Tour
- Rampage 2: Universal Tour
- Rat Attack!
- Rayman 2: The Great Escape
- Razor Freestyle Scooter 
- Re-Volt
- Ready 2 Rumble Boxing 1
- Ready 2 Rumble Boxing Round 2
- Resident Evil 2 (enters ingame, but freezes after some gameplay)
- Ridge Racer 64
- Road Rash 64
- Roadsters Trophy (controller pak error)
- Robot Ponkottsu 64: Nanatsu no Umi no Caramel (J)
- Robotron 64
- Rocket: Robot On Wheels
- Rugrats: Scavenger Hunt
- Rush 2: Extreme Racing USA
- S.C.A.R.S
- Saikyou Haniu Shogi
- San Francisco Rush: Extreme Racing
- Scooby-Doo! Classic Creep Capers
- SD Hiryu no Ken Densetsu (J)
- Shadowgate 64: Trials of the Four Towers
- Shadow Man (Brazil)
- SimCity 2000 (J)
- Sin and Punishment: Successor of the Earth (J)
- Snowboard Kids 1
- Snowboard Kids 2
- South Park (Brazil)
- South Park: Chef's Luv Shack
- South Park Rally
- Space Invaders
- Space Station: Silicon Valley
- Spider-Man
- StarCraft 64
- Star Fox 64 (An issue regarding speed is cutting out a dialogue in Japanese version of the game): https://github.com/ares-emulator/ares/issues/451
- Star Soldier: Vanishing Earth
- Star Wars Episode I: Racer
- Star Wars: Battle for Naboo
- Star Wars: Shadows of the Empire
- Starshot: Space Circus Fever
- Stunt Racer 64
- Super B-Daman Battle Phoenix 64 (J)
- Super Bowling 64
- Supercross 2000
- Superman 64
- Super Mario 64
- Super Mario 64: Shindou Edition(J)
- Super Robot Spirits (J)
- Super Robot Taisen 64 (J)
- Super Smash Bros.
- Susume! Taisen Puzzle Dama: Toukon Marumata Chou (J)
- Taz Express (E)
- Tetris 64 (J)
- Tetrisphere
- Tigger's Honey Hunt
- Tom & Jerry in Fists of Fury
- Tom Clancy's Rainbow Six	 
- Tonic Trouble
- Tony Hawk's Pro Skater 1
- Tony Hawk's Pro Skater 2
- Tony Hawk's Pro Skater 3
- Top Gear Hyper-Bike
- Top Gear Overdrive (All versions)
- Top Gear Rally 1
- Top Gear Rally 2
- Toy Story 2
- Toukon Honoo: Brave Spirits (J)
- Toukon Honoo 2: The Next Generation (J)
- Transformers: Beast Wars Transmetals
- Triple Play 2000
- Turok: Dinosaur Hunter
- Turok: Rage Wars
- Turok 2: Seeds of Evil
- Turok 3: Shadow of Oblivion
- Twisted Edge Snowboarding
- V-Rally Edition '99
- Vigilante 8
- Vigilante 8: 2nd Offense
- Virtual Chess 64
- Virtual Pool 64
- Virtual Pro Wrestling 2: Oudou Keishou (J)
- Virtual Pro Wrestling 64 (J)
- Waialae Country Club: True Golf Classics
- War Gods
- Wave Race 64
- Wave Race 64: Shindou Edition (J)
- Wayne Gretzky's 3D Hockey
- Wayne Gretzky's 3D Hockey '98
- WCW Backstage Assault
- WCW Mayhem
- WCW/NWO Revenge
- WCW vs. NWO World Tour
- Wetrix
- Wheel of Fortune
- Winback: Covert Operations
- Wipeout 64
- Wonder Project J2 (J)
- World Cup '98
- World Driver Championship
- Worms Armageddon
- WWF Attitude
- WWF No Mercy
- WWF War Zone
- WWF Wrestlemania 2000
- Xena Warrior Princess: Talisman of Fate
- Yakouchuu 2: Satsujin Kouru (J)
- Yoshi's Story
- Zool: Majou Tsukai Densetsu (J)

**Partially:**
---
- Blast Corps (some 3D objects are flickering, probably related with RDP freeze): https://github.com/higan-emu/ares/issues/14
- Conker's Bad Fur Day (Graphics issue): https://github.com/higan-emu/ares/issues/186
- Donkey Kong 64 (some 3D objects are flickering, probably related with RDP freeze): https://github.com/higan-emu/ares/issues/14
- Jangou Simulation Mahjong Do 64 (J) (Hangs in "Do you want to change the name?" screen if you don't move the cursor, but plays normally if you do it - rather than just press "A" in this screen)
- Magical Tetris Challenge (Mickey's token corrupted graphics): https://github.com/higan-emu/ares/issues/131
- Mario Party 1 (Slow map transition): https://github.com/higan-emu/ares/issues/135
- Nintama Rantaro 64 Game Gallery (J) (First game hangs): https://github.com/higan-emu/ares/issues/137
- Onegai Monster (J) (Graphics corrupted): https://github.com/higan-emu/ares/issues/139
- WCW Nitro (occasionally hangs after you select a fighter. Wrong emulation speed?)

**Don't work** (hangs in black screen unless another behavior is described)**:**
---
- FIFA Soccer 64
- Gauntlet Legends (The game now boots show some screens, but hangs in the first cutscene): https://github.com/ares-emulator/ares/issues/548
- Jet Force Gemini (Crashes in the intro): https://github.com/higan-emu/ares/issues/129
- Mickey Speedway USA (Crashes in the opening): https://github.com/higan-emu/ares/issues/129
- Pro Mahjong Kiwame 64 (J) (Freezes after "press start" screen)
- Rugrats in Paris: The Movie (Hangs before start the game. May work in interpreter builds)
- San Francisco Rush 2049 (May work in interpreter builds)
- Star Wars: Rogue Squadron (Hangs just after the first cutscene. May work in interpreter builds)

**Comment by jeltaqq** [comment]
Great job!
For Pro Mahjong Tsuwamono 64, select New Game (below) on the title screen. I tested it for a few minutes and had no issues.

**Comment by Shideravan** [comment]
> Great job!

Thanks!

> For Pro Mahjong Tsuwamono 64, select New Game (below) on the title screen. I tested it for a few minutes and had no issues.
You're talking about Pro Mahjong Tsuwamono 64: Jansou Battle ni Chousen, right?
Pro Mahjong Tsuwamono 64
It's freezing for me on this screen, after press start:
![image](https://user-images.githubusercontent.com/12163923/131537332-f8028dba-f5d2-46f8-a726-a47f3c16a1f0.png)

**Comment by Shideravan** [comment]
> Great job!

Thanks!

> For Pro Mahjong Tsuwamono 64, select New Game (below) on the title screen. I tested it for a few minutes and had no issues.

You're right. Thanks for the heads up!

**Comment by remutro** [comment]
This list is fairly close to the already known list of issues, so it would seem that this core has been fairly well covered and everyone's experience is the same (even if you are a little more generous then me declaring "no issues found"  :-)  ) I'm not going to list all the smaller issues identified in addition to this list, but there are a couple of games that have big problems not called out on this list:

- Majora's Mask has an issue with flash saves, it is already captured here: https://github.com/higan-emu/ares/issues/40
- Paper Mario completely skips over the introduction, and if you agree to take the quiz when talking to the very first person you meet, the game locks up. 
- Knife's Edge: Nose Gunner plays way too fast. 
- WCW Nitro: Speed issues, and sometimes will lock up after selecting your character

There are a few additional games that don't save properly (that can't be explained based on the way it is currently handled in Ares), and other minor issues with graphics or audio (not framerate related). And there are a handful of games here that don't hang in interpreter mode but do when using the CPU recompiler (default build)

**Comment by Shideravan** [comment]
> This list is fairly close to the already known list of issues, so it would seem that this core has been fairly well covered and everyone's experience is the same (even if you are a little more generous then me declaring "no issues found" :-) ) I'm not going to list all the smaller issues identified in addition to this list, but there are a couple of games that have big problems not called out on this list:
> 
> * Majora's Mask has an issue with flash saves, it is already captured here: [[N64] Majora's Mask save file duplicates itself #40](https://github.com/higan-emu/ares/issues/40)
> * Paper Mario completely skips over the introduction, and if you agree to take the quiz when talking to the very first person you meet, the game locks up.
> * Knife's Edge: Nose Gunner plays way too fast.
> * WCW Nitro: Speed issues, and sometimes will lock up after selecting your character
> 
> There are a few additional games that don't save properly (that can't be explained based on the way it is currently handled in Ares), and other minor issues with graphics or audio (not framerate related).

You're right, I can replicate everything. I'll update accordingly. Thanks for the heads up!
I initially don't want to include the games going "too fast" in different categories, as everything involving speed and framerate is subject to change as the optimizations need to be done anyway. And also in the present moment is a little hard to check everything with a real hardware capture to see the timing and I would prefer to don't do this based on my own perception. Even there are also other games as I remember that may enter in this category of "speed too fast" too (but I'll include a "speed too fast?" in the list just to mark them on).
WCW Nitro hangs on character selection is also interesting. The first time I experienced I thought I cannot replicate it then I thought that it would be due to an external factor. But yeah, I tested a little here and could replicate the hang again in some tries.

> And there are a handful of games here that don't hang in interpreter mode but do when using the CPU recompiler (default build)

I don't consider that these are usable right now, as there's no way an average user access the interpreter mode in the default build. But I added a small note for the cases I know that they would run in interpreter mode (eg.: Resident Evil 2 and San Francisco Rush 2049) even don't changing the categories they are.

**Comment by remutro** [comment]
Just as an FYI... there appear to be 7 games that hang due to a bug(s) in the CPU recompiler. These games have never hung up on me when compiled using the CPU interpreter (and maybe I have bad luck, it would be nice for others to confirm):

Hydro Thunder
Polaris SnoCross
Resident Evil 2
Rugrats in Paris: The Movie
San Francisco Rush 2049
Star Wars: Rogue Squadron
007 - The World is not Enough

**Comment by remutro** [comment]
Pull request: https://github.com/higan-emu/ares/pull/148 resolves issues with Paper Mario, Derby Stallion 64, Majora's Mask, & Command & Conquer. Please update your list accordingly.

**Comment by Shideravan** [comment]
> Pull request: #148 resolves issues with Paper Mario, Derby Stallion 64, Majora's Mask, & Command & Conquer. Please update your list accordingly.

My pleasure! List updated

**Comment by Shideravan** [comment]
The following games are now playable with #153 
- Battletanx 1
- Battletanx: Global Assault

Some games are now fixed with #156 
- Morita Shougi 64
- Olympic Hockey Nagano '98
- Wayne Gretzky's Hockey 3D
- Wayne Gretzky's Hockey 3D '98

Blast Corps was also promoted from don't work to partially (as it still has graphical issues but at least can enter in-game with the latest fix)

List updated!
Thanks @remutro

**Comment by remutro** [comment]
@Shideravan 

AI Shougi 3 doesn't have background music, even during the intro. It's admittedly weird but that is correct behavior. There are proper sound effects and commentary while in-game. See here: https://www.youtube.com/watch?v=SdFcW-1bNlU

Can you check Morita Shogi 64 (J)  &  Nushi Tsuri 64: Shiokaze Ni Notte (J) again with the latest version? I believe the last round of changes has fixed these games as well (working OK for me). Thanks!

**Comment by Shideravan** [comment]
> AI Shougi 3 doesn't have background music, even during the intro. It's admittedly weird but that is correct behavior. There are proper sound effects and commentary while in-game. See here: https://www.youtube.com/watch?v=SdFcW-1bNlU

The in-game voice clips aren't working in ares.

> Can you check Morita Shogi 64 (J) & Nushi Tsuri 64: Shiokaze Ni Notte (J) again with the latest version? I believe the last round of changes has fixed these games as well (working OK for me). Thanks!

_Morita Shogi 64 (J)_ is working but _Nushi Tsuri 64: Shiokaze Ni Notte (J)_ are still hanging on a black screen. The game _Nushi Tsuri 64_ (no subtitle - which is a different game) is running well though.
![image](https://user-images.githubusercontent.com/12163923/132776154-90f3604e-69a7-446b-88be-b115cdc5155e.png)

Also, I changed the _Wave Race - Shindou Edition_ and _Super Mario 64 - Shindou edition_, as they're now playable with the latest fixes.

**Comment by remutro** [comment]
@Shideravan Hmmmm..... then we have some difference between systems that may be factoring into this (or a bad rom?) Nushi Tsuri 64: Shiokaze ni Notte (J) plays just fine for me:

![image](https://user-images.githubusercontent.com/84990500/132777839-9b8c7fbd-286c-4a55-a459-5de03713fa11.png)

![image](https://user-images.githubusercontent.com/84990500/132779937-4483b3a2-9d2a-4e6b-907a-69e6db983d7a.png)

**Comment by remutro** [comment]
And AI Shougi 3 has all sound effects, as well as commentary when in-game. I'm not sure what the difference is here, but I don't have any problems on my end. Anyone else want to chime in with their experience?

**Comment by Shideravan** [comment]
> @Shideravan Hmmmm..... then we have some difference between systems that may be factoring into this (or a bad rom?) Nushi Tsuri 64: Shiokaze ni Notte (J) plays just fine for me:
> 
> ![image](https://user-images.githubusercontent.com/84990500/132777839-9b8c7fbd-286c-4a55-a459-5de03713fa11.png)
> 
> ![image](https://user-images.githubusercontent.com/84990500/132779937-4483b3a2-9d2a-4e6b-907a-69e6db983d7a.png)

I'm not in my house right now, but for now I'll update with your feedback and check what happened with these games asap

**Comment by Shideravan** [comment]
> And AI Shougi 3 has all sound effects, as well as commentary when in-game. I'm not sure what the difference is here, but I don't have any problems on my end. Anyone else want to chime in with their experience?

Probably it may be related with realtek audio driver which has some issues with ares/higan/bsnes. It even causes audio crackling in most of emulator's audio driver.
I'll update it for now and check later on what's is causing to the audio clips not be executed in my end.

**Comment by Shideravan** [comment]
Jeopardy status updated to reflect changes made with #166

**Comment by remutro** [comment]
@shideravan - the latest changes submitted by invertigo seem to fix the following games:

Turok - Dinosaur Hunter
Forsaken 64
Hercules - The Legendary Journeys
Triple Play 2000
J. League Live 64 (J) 
Tetris 64 (J) 
Taz Express (E) - might need to be patient for that last one, but it does go in-game for me eventually

Additionally, Donkey Kong 64 can get in-game now. If it gets hung up during the intro sequence after selecting a save, if you reset and use the same save then it will start at DKs house after the intro where it got hung up. Still issues with the game (flickering graphics and such).

It might be best for more then one person test and report results, just in case people have different experiences, so it's probably worth a regression at this point to see if there are any negative consequences as the areas touched are quite sensitive to modifications. For instance, Body Harvest has a horrendous framerate for me now. Ares still reports 60 fps, but its more like 1/3 frame-per-second in game. But the more people testing and reporting issues the better so we get accurate results and not one-offs.

**Comment by Shideravan** [comment]
Updated for the status of da53c2b
Also, I bumped Hey You Pikachu and Mario no Photopie, as they don't have emulation issues - they just use peripherals not supported yet.

**Comment by Shideravan** [comment]
> For instance, Body Harvest has a horrendous framerate for me now. Ares still reports 60 fps, but its more like 1/3 frame-per-second in game. 

Yes, I can replicate this. While I say that I would avoid to change the status based in speed, as this game shows 60 FPS, but the speed is incorrect, it's better to mark this as partially for now (probably there's other games with similar issue)

**Comment by Shideravan** [comment]
ares da53c2b
Some games are now running. Note that I didn't did extensive tests to check if they hangs after some gameplay thou.

The following games has been promoted:
* 007 - The World is not Enough (I played for nearly a hour and didn't hang to me in the latest ares da53c2b)
* Donkey Kong 64 - But still has major graphical glitches
* Forsaken 64
* Hercules
* Hydro Thunder
* J. League Live 64
* Polaris SnoCross
* Resident Evil 2 - Now enters ingame, but freezes after some gameplay
* Tetris 64
* Turok Dinosaur Hunter

**Comment by Shideravan** [comment]
If you move the cursor in "Do you want to change the name?" screen in "Jangou Simulation Mahjong Do 64" it doesn't hangs in black screen. You can select either one, but needs to move the cursor. Thus I'm promoving this game to "partially"
![image](https://user-images.githubusercontent.com/12163923/134785689-628a3579-348e-437e-8aa1-4e468299f035.png)

**Comment by remutro** [comment]
@Shideravan 

Both Michael Owens WLS 2000 (E) & Top Gear Overdrive (Europe) can be moved from the broken to working list.

**Comment by itwasall** [comment]
v127 - **Paper Mario** no longer skips the intro, game appears to be behaving normally. No freezes detected, saving also works.

**Comment by Shideravan** [comment]
ares [da53c2b](https://github.com/ares-emulator/ares/commit/3aa1b3b7389dffd0aff4f432de62f0ec9e764c8b)
With the recents updates from @rasky some games are now running. Note that I didn't did extensive tests to check if they hangs after some gameplay yet (if this is the case for any game, please report).

The following games has been promoted to no issues found:
* A Bug's Life
* Indiana Jones and the Infernal Machine
* Star Wars: Battle for Naboo
* Toy Story 2

Updated but not promoted:
* Gauntlet Legends (it now can now show some screens, but hangs after the first cutscene)

Demoted:
* Donkey Kong 64: Now hangs just after Rareware logo https://github.com/ares-emulator/ares/issues/539

**Comment by Shideravan** [comment]
Adding the Star Fox 64 issue reported here: https://github.com/ares-emulator/ares/issues/451

**Comment by kev4cards** [comment]
The following games all had some sort of hang either in-game or before and are now seemingly more stable and fixed as of commit bcf9cab: Star Wars- Rogue Sqaudron, Rugrats in Paris- The Movie, Hydro Thunder, Polaris SnoCross, 007 - The World is not Enough, and Resident Evil 2.

San Francisco Rush 2049 can reach in-game but hangs a few minutes into the race. If you are unlucky, it can still hang in the menu screen. The aforementioned commit is responsible for this improvement, too.

**Comment by LukeUsher** [comment]
Superseded by the compatibility section on the ares website
