### ISSUE TITLE
[PCE] Issues with multi-tap (Can crash the emulator if you try to conect a multi-tap on a multi-tap slot)

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#145]
After the multi-tap implementation update, is no longer possible to connect the turbo control directly to Port 1 without multitap. 
Also, plug another multi-tap in any of the slots of the multi-tap makes ares crashes instantly.
![image](https://user-images.githubusercontent.com/12163923/131510957-a4874864-93f9-406d-a804-33001ec1b2b6.png)
AFAIK there's no game in PCE/Turbografx 16 which supports more than 5 players simultaneously and I think that maybe this option shouldn't exist

https://www.sega-16.com/forum/showthread.php?19158-Need-some-multi-player-Turbo-Engine-games/page2
https://blackfalcongames.net/?p=155

(and shouldn't better idea to rename "controller port n" as "multi-tap port n" to avoiding name confusion?)

**Comment by LukeUsher** [comment]
The primary issue here is that ares itself was not really designed for the scenario of multi-taps; this was something more geared to the more complex UI as found in 'higan'.

This will take some thinking and potentially major restructuring in the input handling to solve gracefully.

**Comment by LukeUsher** [comment]
Avoided with 4146f9d, achieved by blacklisting multi-tap from the input selection, and hiding the system native 'controller port'

This means the multi-tap is always connected, and you can configure ports 1-5.
