### ISSUE TITLE
[PS1] PlayStation core known compatibility issues

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#150]
As the core isn't mature enough and a lot of games are known to won't working well, together with the fact that nobody is actively working on this core right now, this topic will work better as a single issue in our GitHub to avoid potential flood in the platform. If you know a game that has any issue in PlayStation core, just reply to this issue and I'll be glad to include it in the following list for further reference:

Partially
---

* Crossroad Crisis (USA) - Flickering graphics, still playable.
* Family Diamond (Japan) - Blue screen on character select, disappears when directional buttons are pressed
* Final Round, The (USA) - Flickering graphics, still playable.
* Finger Flashing (Japan) - Flickering graphics, still playable.

Not working:
---

* Aqua GT (Europe) - Black screen.
* Dragon Warrior VII (U) - Fails to boot (black screen) :-(
* Fun! Fun! Pingu: Youkoso! Nankyoku e (Japan) - black screen on starting a new game
* Kyuutenkai (Japan) - Garbled noise, the game does not get past menus, as it's stuck whilst loading.

**Comment by meowthed** [comment]
Family Diamond (Japan) - Blue screen on character select, disappears when directional buttons are pressed
![Untitled](https://user-images.githubusercontent.com/41223243/131762218-22db7686-6896-4be0-8846-fe8473f0ee81.png)

**Comment by meowthed** [comment]
Kyuutenkai (Japan) - Garbled noise, game does not get past menus, as it's stuck whilst loading.
![Untitled](https://user-images.githubusercontent.com/41223243/131764286-02c6fb52-c8b9-4666-b5ac-14c11542c63c.png)

**Comment by remutro** [comment]
Dragon Warrior VII (U) - Fails to boot (black screen) :-(

**Comment by meowthed** [comment]
Aqua GT (Europe) - Black screen.
Crossroad Crisis (USA) - Flickering graphics, still playable.
Final Round, The (USA) - Flickering graphics, still playable.
Finger Flashing (Japan) - Flickering graphics, still playable.

**Comment by LukeUsher** [comment]
Closing this issue as compatibility info is now tracked on the website.
