### ISSUE TITLE
[MD] Where in time is Carmen Sandiego: Corrupted audio

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#155]
The SFX in this game is completely messed in elevator.
Tested with WASAPI, DirectSound, waveOut, and XAudio audio drivers.
ares 4146f9d
Windows 10 x64

**Comment by TascoDLX** [comment]
I believe this is fixed with #257, but please verify.

**Comment by Shideravan** [comment]
> I believe this is fixed with #257, but please verify.

Yes, it's fixed now. Thank you!
