### ISSUE TITLE
new system: Arcade

### ISSUE THREAD

**Issue by soundsnow** [ares-emulator/ares#1565]

**Comment by asiekierka** [comment]
As much as I respect reaching out to Ares, I do not think the project has the budget, development capacity, or interest in becoming MAME.

**Comment by soundsnow** [comment]
> As much as I respect reaching out to Ares, I do not think the project has the budget, development capacity, or interest in becoming MAME.

what's this? https://ares-emu.net/compatibility/arcade-arcade
SC-3000 computer hardware arcade games, this page cannot have only three games, ares supports so many game console hardware. MAME’s game console compatibility is not as good as ares
Arcade - Arcade is too long a name

**Comment by asiekierka** [comment]
> what's this? https://ares-emu.net/compatibility/arcade-arcade

Games for the lightly modified arcade variant of the SG-1000 video game console.

It didn't have the budget or development capacity issue, because the differences between the SG-1000 and SG-1000A are minimal.
