### ISSUE TITLE
console and arcade

### ISSUE THREAD

**Issue by soundsnow** [ares-emulator/ares#1611]
https://emulation.gametechwiki.com/index.php/GCA3A#Console_2
3DO
- M1? and Atari
- M2? and Konami

Atari
- 2600
- Jaguar

Bally
- Arcade and Bally Midway

Microsoft
- Xbox and Sega

NEC
- PC Engine and Data East
- PC Engine and Capcom

Nintendo
- Famicom
- 64 and Seta / Aruze
- GameCube and Capcom? / Sega / Bandai Namco
- Wii and Capcom

Sega
- SG-1000
- Master System
- Mega Drive and Data East
- Saturn
- Dreamcast and Sega Sammy

SNK
- NeoGeo and Andamiro
- NeoGeo and SNK Playmore

Sony
- PlayStation and Namco
- PlayStation and Konami
- PlayStation and Taito, Capcom, Acclaim, Time Warner, Atlus, Video System, Eighting, Tecmo
- PlayStation 2 and Bandai Namco
- PlayStation 2 and Konami
- PlayStation 3 and Bandai Namco

**Comment by Kawa-oneechan** [comment]
> I do not think the project has the budget, development capacity, or interest
— @asiekierka 

What makes you think we have the budget, capacity, or interest in supporting the... \*picks a system at random* _PlayStation 3_, Snow?

**Comment by soundsnow** [comment]
Because ares is a multi-system emulator and supports arcade games for SG-1000 hardware. No one said ares has to not support newer game consoles like the PS3, and to make it seem more complete, I'm including the PS3 because it has arcade games. If ares only supports arcade games related to old consoles, that's fine too

**Comment by LukeUsher** [comment]
You do realise most of the arcade systems based on these consoles are very different from these consoles right? There’s a reason most game console emulators can’t also play arcade games for related systems. 

“Based on” in this case usually means “shares some hardware or design concepts with”
