### ISSUE TITLE
[GBC] Tomb Raider - Curse of the Sword: hangs in opening

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#162]
Hangs in this screen:
![image](https://user-images.githubusercontent.com/12163923/132719540-1bc29f7f-f40a-4b97-a151-5ad182533f08.png)

**Comment by invertego** [comment]
You can advance past the text by pressing A.

**Comment by Shideravan** [comment]
I really hate the inconsistency in the controllers when testing in different cores...
