### ISSUE TITLE
[GBA] Final Fantasy V Advance hangs

### ISSUE THREAD

**Issue by Carmina16** [ares-emulator/ares#168]
Ares 123
ROM: 492789276eaa3e94152b143ad92f310b8a3d5366
Bios: 300c20df6731a33952ded8c436f7f186d25d3492

Combat makes the game to hang.
[state.zip](https://github.com/higan-emu/ares/files/7149609/state.zip)

**Comment by LukeUsher** [comment]
Can you confirm this is still an issue?

Also does it only impact one region, or does the issue exist for USA, Japan and Europe too?

**Comment by Carmina16** [comment]
Affects EU version in the recent version too.

**Comment by LukeUsher** [comment]
It's been a long time but I am unable to reproduce in the latest nightly; I played up until meeting the pirates; which I'll admit is not a long time but there was a number of random battles in that time, without issue.
