### ISSUE TITLE
[MD] McDonald's Treasure Land Adventures: Graphical glitches in special 3D mode

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#176]
How to start the 3D mode?
1. Put this password
![image](https://user-images.githubusercontent.com/12163923/133141157-a86281df-51a6-472f-bee6-85c7c690ee81.png)
2. Press start 3 times
3. Just when you hear explosion sound, press Left+Up. Maintain it pressed until the mode starts.

The 3D image has some graphical glitches
![image](https://user-images.githubusercontent.com/12163923/133141501-54fb3ae9-3680-42e0-aa01-342fa44ce0ac.png)

Example of the expected behavior:
https://www.youtube.com/watch?v=BvGC5dJg3E8

**Comment by BiZkViT96** [comment]
Maybe present on a real MD.

https://youtu.be/ItIakKXuijo?t=120

**Comment by BiZkViT96** [comment]
Not a emulator bug. Exists on real MD. The game shows a different level of glitches depending on the region of NTSC vs PAL. Confirmed by TascoDLX.
