### ISSUE TITLE
[MD] Forgotten Worlds: Instant Game Over screen on start of the gameplay segment

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#177]
![image](https://user-images.githubusercontent.com/12163923/133169240-d4f575ea-28e5-43cb-b6c1-75f237d2e804.png)

**Comment by sikthehedgehog** [comment]
This game breaks like that when using a 6-button controller.

**Comment by Kawa-oneechan** [comment]
From the Sega-16 forums. I don't know if "hold MODE" is an option here but it's nice to have confirmation.

> Method # 2 - Find the MODE button on your 6-button controller and hold it down before you turn the power on to your Genesis/Mega Drive. While still holding it down, turn your Genesis/Mega Drive on. At any time after the Genesis/Mega Drive is fully on (LED on the system is lit, etc), let go of the MODE button. Forgotten Worlds now works fine and won't go into retard mode. Why is this? It's because the MODE button switches a 6-button controller to 3-button mode if it is held down when power is first applied. Many games need this.
> 
> Other games that require a 3-button controller or the MODE button method:
> Ms. Pac Man
> Beast Wrestler
> Sunset Riders
> Golden Axe 2
> Exile
> John Madden Football

**Comment by Shideravan** [comment]
Fixed with https://github.com/higan-emu/ares/pull/197
