### ISSUE TITLE
32X sound is broken in Windows CI builds of ares

### ISSUE THREAD

**Issue by remutro** [ares-emulator/ares#227]
Playing any 32X game using the Windows CI builds of ares results in corrupted sound. This has been observed by a number of people. When building locally 32X sound works just fine on Windows ( in my instance - mingw64 & gcc 10.3). This could be due to the compiler Github is using to build the project.

Anyone downloading Windows builds as opposed to building themselves is going to think sound does not work properly for 32X games when in fact it works just fine for the majority of games.

**Comment by Shideravan** [comment]
The performance in the CI builds are significant slower, more yet in demanding systems such as 32X and N64.
I don't know why, but compiling locally using _lto=false_ makes the performance a lots better.

**Comment by invertego** [comment]
I believe this is fixed by #230

Can either of you try this build: https://github.com/ares-emulator/ares/suites/4069491900/artifacts/103456300

I'm getting nearly double performance of the latest release with the 32x core on that build (using GCC 10.3.0), which is enough to clean up the crackly audio, at least on my machine.

**Comment by cjalbert** [comment]
@Invertigo, the build you provided works just fine on my system with 32X audio. As suspected, it was likely do to the compiler version, 8.1.0 is fairly old now. It's in sync with my system now, and these builds work great. Thanks!

Heh...logged into wrong github account for this. I've done this a couple times, but cjalbert == remutro  :-)

**Comment by oldschoolsysadmin** [comment]
Wrong @invertego, @cjalbert ;-)

**Comment by LukeUsher** [comment]
fixed by #230
