### ISSUE TITLE
ares v124 fails spc7110 test

### ISSUE THREAD

**Issue by galtgendo** [ares-emulator/ares#228]
In the first batch of tests, 'D-Port B+O+S' fails.

Though if you have an intact old save, you'll likely won't notice.

Also, might just be me hearing things, but audio seems lagging badly in that game  - other games don't give such feeling.
Could it be that the decompression, while fast, still manages to eat enough cycles to slow things down ?

**Comment by LukeUsher** [comment]
solved in #271
