### ISSUE TITLE
Master System - There is no option to make specific input mapping changes

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emulator/ares#23]
There is no option to make specific input mappings for Master System except pause and reset buttons.
See attached image
![TT](https://user-images.githubusercontent.com/87193210/127498279-cc82a8e7-e183-4297-8d0d-5ebd54c79b15.png)

**Comment by Kawa-oneechan** [comment]
Try "Controller Port 1". You're looking at the buttons on the system itself.

**Comment by Yotamtamtam** [comment]
True. I didn't notice that, especially that in any other core the default is on controller port 1.
I guess it's not a bug, but more of a less good user interface.
