### ISSUE TITLE
[MD] Double Dragon: Doesn't launch

### ISSUE THREAD

**Issue by BiZkViT96** [ares-emulator/ares#250]
I hope the developers don't mind that I'm spamming bug reports like this. 

Ares - Black screen
![2021-10-19 20_28_21-Double Dragon (U)  !](https://user-images.githubusercontent.com/88586431/137919659-8a8b42fd-7baf-4e7d-980a-c63ccae4a4a2.png)
Kega - in game
![2021-10-19 20_27_45-Fusion 3 64 - Genesis - DOUBLE DRAGON](https://user-images.githubusercontent.com/88586431/137919739-404c1b7e-37a8-421f-949d-f7f3d38a176c.png)

Double Dragon (U) [!]
SHA1 F054FB2C16A78CE5F5CE20A36BF0F2634F169969

Tested on ares nightly 2021-10-19

**Comment by FitzRoyX** [comment]
Make sure you include the (Unlicensed) or (Proto) tags when a game is of that type. Sometimes that has a lot to do with why a game isn't working.

**Comment by TascoDLX** [comment]
IMO you don't really need to post screenshots for simple issues like this. It's enough to say 'ares boots to black screen, but the rom boots fine in Fusion, BlastEm' or whatever, as that typically doesn't require illustration. If you're going to add anything, please include the full rom name and crc/sha hash if possible so we know exactly what you're testing.

Nevertheless, thank you for the report, this will be fixed shortly.

**Comment by BiZkViT96** [comment]
@TascoDLX Okay, I'll keep that in mind. I hope Ares will replace Kega as a universal emulator for pre 32Bit Sega systems. Thanks.

@FitzRoyX In this case, it is retail.

**Comment by BiZkViT96** [comment]
Fixed with https://github.com/ares-emulator/ares/pull/257
