### ISSUE TITLE
[N64] SD Quality renderer is causing some games crash in Windows systems 

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#254]
The issue was reported by another person unsing Windows 11, but was replicated by me with these configs:

**Top Gear Overdrive (Europe)**
*To replicate, just select Championship or Versus mode in the main menu. ares Crashes immediately.*
Version: Europe only, USA and Japan runs fine.
SO: Windows 10 x64
MD5: 6C65A252F227AEF18DF2DD3CE04CC821
ares v124

Edit: I'm adding Michael Owens WLS 2000 (Europe) and closing that issue, as both issues seems to be very related.

**Michael Owens WLS 2000 (Europe)**
*The emulator crashes immediatelly when try to load this game*
Version: Europe only. Other versions/variants of this game runs fine. 
SO: Windows 10 x64
MD5: 892222CC4BAF9958405D20BC492175BF
ares v124

Issue closed:
https://github.com/ares-emulator/ares/issues/136

If another game with the same issue is found, I'll edit this issue to include them as a way to centralize our analysis. 
If you know another N64 game with the same issue, please report here to ease the tracking down.

**Comment by remutro** [comment]
I was just about to add a comment that I couldn't reproduce this issue, screenshots and everything. But I decided to do one last thing and now I can reproduce the crash. I haven't encountered this before, but I will likely go back and test a few games now that I know this seems to makes a difference. This game ONLY crashes for me when using the standard SD resolution. If I set this game to either HD or UHD quality, it runs just fine (Settings > Video). Curious if this works for others as well. 

Also, how great is the soundtrack to this game! :-)

Edit: Same scenario with this reported crash. No issues in HD or UHD, only SD: https://github.com/ares-emulator/ares/issues/136

**Comment by remutro** [comment]
This issue and #136 are the same issue. Segfault is exactly the same on the same line of code:

Thread 28 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1548.0x4b1c]
0x00007ff6d3a076e4 in ares::Nintendo64::VI::refresh (this=0x7ff714ae17e0 <ares::Nintendo64::vi>) at ../ares/n64/vi/vi.cpp:94
94	          target[x] = source[x * 4 + 0] << 16 | source[x * 4 + 1] << 8 | source[x * 4 + 2] << 0;

These could probably be merged into one issue, and both games can be referenced. Assuming your hardware can support it, setting Video to HD is a valid workaround.

**Comment by bigbass1997** [comment]
Just like the other issue, I cannot reproduce the crash. I tested with SD, HD, and UHD.

OS: Linux Mint 20.2
MD5: 6C65A252F227AEF18DF2DD3CE04CC821
Using latest master commit

**Comment by remutro** [comment]
> Just like the other issue, I cannot reproduce the crash. I tested with SD, HD, and UHD.
> 
> OS: Linux Mint 20.2 MD5: 6C65A252F227AEF18DF2DD3CE04CC821 Using latest master commit

@bigbass1997  I'm assuming you are still running in a VM with video drivers that don't support Vulkan, correct?

**Comment by bigbass1997** [comment]
> > Just like the other issue, I cannot reproduce the crash. I tested with SD, HD, and UHD.
> > OS: Linux Mint 20.2 MD5: 6C65A252F227AEF18DF2DD3CE04CC821 Using latest master commit
> 
> @bigbass1997 I'm assuming you are still running in a VM with video drivers that don't support Vulkan, correct?

No. My native system is linux as noted (which does support vulkan). Not running in a VM. For the Michael Owens game, I did additionally try testing in a Windows VM, but I didn't try that for this Top Gear game.

**Comment by Shideravan** [comment]
As requested, I merged #254 and #136 as we found that both are very similar and very probably related.
I also think it's a better idea centralize our analysis and any new information in the same issue.
