### ISSUE TITLE
[MD] Resistance The Spiral (Demoscene): Doesn't launch

### ISSUE THREAD

**Issue by BiZkViT96** [ares-emulator/ares#261]
Just black screen. Demo here https://www.pouet.net/prod.php?which=82607

Works fine on BlastEm and Kega.

The_Spiral_by_Resistance_2019_60Hz
SHA1 EBD51FD1FF293D3071D443D59E009F72DA0B4B14

Tested on ares nightly 2021-10-21

**Comment by LukeUsher** [comment]
fixed by #267
