### ISSUE TITLE
Big slowdowns in Ocarina of Time

### ISSUE THREAD

**Issue by brendynw** [ares-emulator/ares#27]
been playing through OOT and getting some pretty serious slowdowns in certain spots. The actual hardware would drop a little occasionally but nothing as severe as this.

A couple examples are in Jabu Jabu's Belly the central room that branches off into 3 halls, once the 3 electric worms that come out to fly in the middle the framerate nearly cuts in half

and in the Shadow Temple once you board the ship, once the second Stalfos drops down the framerate drops significantly, and you can find a save state for that one right here:
https://drive.google.com/file/d/1Alj-EQ5t6uklBjK2bybA5ihP8Idvt2xT/view?usp=sharing

I'm using the NoIntro v1.0 ROM

**Comment by LukeUsher** [comment]
First, we need to determine what you mean specifically by big slowdowns/framerate drops.

There are two scenarios

1. The framerate counter in ares shows a framerate of < 60fps
2. The framerate counter in ares remains a solid 60fps, but the game slows down regardless

Scenario 1 would just mean that your hardware isn't capable of maintaining full-speed in the ares n64 core yet; this isn't completely unexpected as it is relatively new, very demanding, and still under development, in this scenario, all you can do is wait for ares to become more optimised, or upgrade your machine.

Scenario 2 would mean that ares is running the emulated n64 too slow; this would be a real bug, most likely caused by imperfect emulation of the timing between components and/or details such as the CPU cache. As far as I'm aware, it is not currently understood exactly what these values should be, so there has been a little bit of trial/error and educated guesses involved.

Knowing which scenario this is would help us determine how to proceed going forward

**Comment by brendynw** [comment]
It is definitely the latter scenario, the fps counter stays locked to 60fps regardless of what the performance looks like

I went back and grabbed a save state for the room in Jabu Jabu's belly if that's helpful as well, which I will link here;
https://drive.google.com/file/d/1sc7ndojP-_t3AqZqGIJRJwowvYeEulZZ/view?usp=sharing

The slowdown isn't nearly as drastic as I made it sound in my original post but it is still very noticeable.

For what it's worth the same areas which give slowdown also seemingly run at full speed on m64p, but idk if that emulator shares enough in common with ares for that info to be useful.

This is a great emulator though, keep up the great work!

**Comment by Shideravan** [comment]
> been playing through OOT and getting some pretty serious slowdowns in certain spots. The actual hardware would drop a little occasionally but nothing as severe as this.
> 
> A couple examples are in Jabu Jabu's Belly the central room that branches off into 3 halls, once the 3 electric worms that come out to fly in the middle the framerate nearly cuts in half
> 
> and in the Shadow Temple once you board the ship, once the second Stalfos drops down the framerate drops significantly, and you can find a save state for that one right here:
> https://drive.google.com/file/d/1Alj-EQ5t6uklBjK2bybA5ihP8Idvt2xT/view?usp=sharing
> 
> I'm using the NoIntro v1.0 ROM

Which version of emulator was used for this savestate? It's not working with the latest ares using Legend of Zelda, The - Ocarina of Time (USA).z64 from No-intro (MD5: 5BD1FE107BF8106B2AB6650ABECD54D6)
![image](https://user-images.githubusercontent.com/12163923/128409521-f8fe98f5-0f66-4da6-9d05-a2eae98506ea.png)

**Comment by combo-pizzaroll** [comment]
Here's a video of the second stalfos on a real n64 with a 1.0 US cart. I have no dump of the game though so I can't test it in ares, but maybe this will help you out

https://www.youtube.com/watch?v=ibJvIBFEQUQ

**Comment by brendynw** [comment]
> Which version of emulator was used for this savestate? It's not working with the latest ares using Legend of Zelda, The - Ocarina of Time (USA).z64 from No-intro (MD5: 5BD1FE107BF8106B2AB6650ABECD54D6)
> ![image](https://user-images.githubusercontent.com/12163923/128409521-f8fe98f5-0f66-4da6-9d05-a2eae98506ea.png)

That specific one may have been from 121a, the second one I linked is from 122 though I just grabbed it this morning. if that doesn't work I'll have to try making a new one once I'm home later.

**Comment by bigbass1997** [comment]
> For what it's worth the same areas which give slowdown also seemingly run at full speed on m64p

I definitely wouldn't trust m64p as an example of what is/isn't accurate behavior. It's probably a timing bug (Scenario 2 that LukeUsher said), and if that's the case, I'd be interested in knowing what sort of operations the game is performing during these slowdowns. It may help be an indicator of where the inaccuracy is coming from.

(Though, if it is a DMA inaccuracy, it'll probably be rather hard finding a fix that also doesn't break other games in the process)

**Comment by brendynw** [comment]
> Which version of emulator was used for this savestate? It's not working with the latest ares using Legend of Zelda, The - Ocarina of Time (USA).z64 from No-intro (MD5: 5BD1FE107BF8106B2AB6650ABECD54D6)
> ![image](https://user-images.githubusercontent.com/12163923/128409521-f8fe98f5-0f66-4da6-9d05-a2eae98506ea.png)

Weird that it's not working for you, I'm having no issue loading the save state on 122. And I am using the same ROM, MD5 verified
![image](https://user-images.githubusercontent.com/59981980/128438233-d79e61f5-babd-4458-bf77-1c2c8e2abb55.png)

> I definitely wouldn't trust m64p as an example of what is/isn't accurate behavior. It's probably a timing bug (Scenario 2 that LukeUsher said), and if that's the case, I'd be interested in knowing what sort of operations the game is performing during these slowdowns. It may help be an indicator of where the inaccuracy is coming from.
> 
> (Though, if it is a DMA inaccuracy, it'll probably be rather hard finding a fix that also doesn't break other games in the process)

It doesn't seem to be any operations in particular, it just seems to be whenever you enter an area with a good handful of enemies. The biggest slowdown I got while I was playing was in the Forest Temple after I beat the two Stalfos to get the bow. After defeating them and their bodies fell apart the framerate seemed to grind to a halt until all the pieces despawned.

It's been several years since I last played this on an actual console, and if this is accurate to how it behaves on hardware then obviously I'm wrong and there's no problem but I never remember the game slowing down this much personally. Thanks for all the replies though regardless!

**Comment by ghost** [comment]
Well games could get around 10 to 15 fps sometimes on the real thing. I think some games could even run below that but were usually an unplayable mess. If you throw out enough explosions in golden eye for example the game becomes so slow you can barely move around. Mupen64, project64 and even nintendos ports are not a good reference at all for how the games ran. I imagine proper over clocking could get a similar effect to the count register hack that most n64 emulators use.

**Comment by remutro** [comment]
What are your system specs? I don't seem to experience the same slow down you are suggesting. I've tried loading your save state multiple times against the latest master build and I haven't witnessed any problems. I've also recently completed a 100% run through this game (although it was against Ares v119, so its possible something changed since then) and never encountered unexpected problems.

**Comment by brendynw** [comment]
> What are your system specs? I don't seem to experience the same slow down you are suggesting.

r5 3600, 32gb ram, 2070 super

Like I said before, the fps counter in the bottom corner stays locked to 60 whenever this happens. To my understanding if it was my computer falling behind the fps counter would drop.

**Comment by combo-pizzaroll** [comment]
Second one isn't a bug, it's slow on the real system when two Stalfos are on the screen at the same time. I didn't notice it before because I had defeated the first one before the second one appeared.

**Comment by combo-pizzaroll** [comment]
Okay this is so strange after playing around with both for awhile. Ares is certainly doing something wrong, It's slowing down in different spots in jabu jabu compared to a real n64. I'm going to say it's a bug but seems like it would be difficult to fix with out any kind of hardware testing.

**Comment by ghost** [comment]
Sorry that I keep changing my post. Jabu Jabu seems like a good place for someone to do timing tests in since it behaves differently in ares and on the real system. I'm sure other games are affected by this too. Anyway it's certainly a bug.

**Comment by bigbass1997** [comment]
> since it behaves differently in ares and on the real system

Behaves differently in what way? Can this behavior be seen in any other emulators?

**Comment by ghost** [comment]
It slows down in different areas inside jabu jabu with an added bonus of slowing down too much in ares 1.22. No emulator replicates this behavior properly. Ares is probably the closet to being like the real thing, then again I haven't tested mame or cen64 either but they don't run fast enough on my pc anyway so it would be hard for me to tell.

**Comment by kev4cards** [comment]
No slowdown present in Jabu Jabu's Belly in the room with three paths and the electric worms as of commit 6bf0d1f. @BrendynW Could you please confirm? Using these two builds should suffice: https://github.com/ares-emulator/ares/actions/runs/5775736329 and https://github.com/ares-emulator/ares/actions/runs/5784536862 .

**Comment by LukeUsher** [comment]
based on the latest comment + lack of feedback recently, I feel like we can close this issue.
The n64 has gone under dramatic development since this issue is created, it is unlikely it will still exist in the same form.
