### ISSUE TITLE
[N64] Factor 5 games doesn't work properly

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#32]
All 3 Factor 5 games aren't booting properly.
Probably it's due Factor 5 microcode implementation in such games.

* Indiana Jones and the Infernal Machine: Black screen
* Star Wars: Battle for Naboo: Black screen
* Star Wars: Rogue Squadron: Crashes just after the first cutscene

There is other games that uses Factor 5 microcode sound compression technology which also don't work properly, but i'm unsure if it is microcode related:

* Resident Evil 2 (uses Factor 5 sound compression technology): Black screen after starts a new game
* San Francisco Rush 2049 (uses Factor 5 sound compression technology): Freezes just after the first screen

But **Pokémon Stadium 1** and **Elmo's Letter Adventure** which are at least said in internet that uses Factor 5 sound compression techlonogy (but I'm not sure about this claim) don't seem to have any issues (regard performance).

Version tested: Ares 1.22 (official)
SO: Windows 10 x64

**Comment by LukeUsher** [comment]
With ares being an LLE emulator, rather than an HLE emulator for N64, it doesn't suffer from the same 'incorrectly/bad implemented microcode' issues that HLE emulators are notorious for, so while these games are not working, the cause is almost certainly something other than this.

**Comment by Shideravan** [comment]
Very nice side effect then :)

**Comment by remutro** [comment]
This statement does not apply to Indiana Jones or Battle for Naboo (these are 2 out of 6 games that have never booted in Ares from the USA ROM set for unknown reasons at the moment, the other 4 being: A Bug's Life, Gauntlet Legends, FIFA Soccer 64, & Toy Story 2). 

However, the crashes/hangs in Rogue Squadron, Resident Evil 2, & San Francisco Rush 2049 are all CPU recompiler bugs. If you compile Ares with the CPU interpreter instead, these hangs no longer exist. Of course this will cause performance loss. The RSP recompiler does not appear to introduce any known issues at this time (reverting to its interpreter mode doesn't fix anything).

The CPU recompiler bug(s) also impacts the following games (they will hang):
007 - The World is not Enough
Polaris SnoCross
Rugrats in Paris: The Movie
Hydro Thunder

And yes, the majority of these seem to make use of MusyX technology.

**Comment by Shideravan** [comment]
How do I can reproduce the bug in 007 - The World is not Enough? It's seem running fine for me

**Comment by remutro** [comment]
> How do I can reproduce the bug in 007 - The World is not Enough? It's seem running fine for me

I just played this game again using the latest build and after about 10 minutes of gameplay it locked up again while working through the first mission.

**Comment by remutro** [comment]
All but Rogue Squadron works as of v129. And we have had that working, we know it is related to incorrect timing issues. We probably don't need to keep this open.
