### ISSUE TITLE
[N64] Majora's Mask save file duplicates itself

### ISSUE THREAD

**Issue by brendynw** [ares-emulator/ares#40]
When you create a new save, the save file immediately duplicates to the second slot as well. It doesn't matter if you delete it or not, the file always comes back when you return to the file select screen. You can even try to erase it and start a new file in the second slot, but when you start the new file it will just load the original one.

EDIT: If you save at an owl statue it seemingly uses the duplicate save file for that too, as the owl icon appears near the second file after you quit, not the original

I hesitated to put this here because it seemed like it must be something other than the emulator that's causing this, but it doesn't happen with any other emulator.

Here is my save file and a save state from right after the duplicate has been deleted;
https://drive.google.com/file/d/19BhGZkFrLaxc-MfEQt5p8zCB4kV_187K/view?usp=sharing

To replicate all you have to do is back out to the title screen and then proceed back to the file select. You'll see the original save file duplicated to the second slot on its own.

I'm using the NoIntro ROM
MD5: 2a0a8acb61538235bc1094d297fb6556

**Comment by Shideravan** [comment]
Yes, I can replicate
![image](https://user-images.githubusercontent.com/12163923/131595463-956bcbb5-d113-464a-ab1f-1b2967a774bc.png)

**Comment by jeltaqq** [comment]
This PR https://github.com/higan-emu/ares/pull/148 will one save. Testing is welcome.

**Comment by Shideravan** [comment]
Fixed with PR #148 
![image](https://user-images.githubusercontent.com/12163923/131751059-b6c5a67f-9c12-4df1-9372-bc798c3d8f87.png)
