### ISSUE TITLE
[MD] Gunstar Heroes: Graphic flickering

### ISSUE THREAD

**Issue by BiZkViT96** [ares-emulator/ares#412]
During the cutscenes, there are two flickering lines at the top and bottom of the picture.

Real hardware has a slight flicker on top of the screen with "Your journey ends here!". The flicker is minor and lasts 1-2 seconds and never appears at the bottom of the screen. BlastEm has exactly the same flicker as real hardware.

Ares at the same time has a strong flicker throughout **all** cutscenes.

![ares_2022_02_24_14_09_05_989](https://user-images.githubusercontent.com/88586431/155477642-2e01f09d-1c64-41ec-9994-02556e9d34f7.gif)

What is interesting, @Shideravan on 27 Aug 2021 in #22 said "I also tested all the treasure games too and didn't find any bugs." but this bug has always been there as far as I can tell.

I beat two bosses and didn't notice any other bugs.

Gunstar Heroes (USA)
SHA1 7721e302555f16e3242ad4a47ed87a1de1882122

Tested on ares nightly 2022-02-23

**Comment by Shideravan** [comment]
> What is interesting, @Shideravan on 27 Aug 2021 in #22 said "I also tested all the treasure games too and didn't find any bugs." but this bug has always been there as far as I can tell.

I'd just like to point out that it's not because I didn't realize at the time that it would mean the bug didn't exist. The context was more like "I couldn't identify bugs in these games. Do they no longer exist or should I do something more specifically?" 
That said, good report!
