### ISSUE TITLE
Using throught command line

### ISSUE THREAD

**Issue by ameliandev** [ares-emulator/ares#48]
Hi, thanks for your work in this emulator, it's awesome.

I would like to know if it's possible to use emulator throught command line. I tried with ngp color rom and the emulators open, but run in directly as monocrome game.

```
C:\<emu_path>\lucia.exe game.ngp
```

Thanks

**Comment by Screwtapello** [comment]
Are you sure it's an NGPC game? If it ends with `.ngp`, that sounds like a regular Neo Geo Pocket game, NGPC games typically end with `.ngc`.

**Comment by Shideravan** [comment]
What game is it? 
It seems that the way you're doing is correct, assuming the game is in the same directory as the emulator itself. 
That said I ain't sure if Ares already has a proper command to select the system in the command line before loading the game and by default, it seems to be linked to the ROM extension. eg.: if I use a GameBoy game with GBC extension it's ever running using the Game Boy Color driver, even if the ROM is a Classic Game Boy game. The same if I rename it to .bin, it even tries to load as a Mega Drive game.
If your game was designed for Neo Geo Pocket Color, maybe you can just rename it to .ngc and be loaded in the correct drive.
Also an extra tip: next releases after the v122 the .exe will be called ares.exe by default (as the development build and the nightly builds just after the v122 already are).

**Comment by ameliandev** [comment]
Hi again. Well I tried it with a ngc extension and works perfectly. 

@Shideravan thanks for the extra tip! I'm using this "lucia.exe" to make debug of my NGPC game and the compiler launch the <emu_path>\lucia.exe "myrom.ngc" and, if in the future change it, I must change de compiler config.

Many many thanks for your reply

**Comment by ameliandev** [comment]
> What game is it?
> It seems that the way you're doing is correct, assuming the game is in the same directory as the emulator itself.
> That said I ain't sure if Ares already has a proper command to select the system in the command line before loading the game and by default, it seems to be linked to the ROM extension. eg.: if I use a GameBoy game with GBC extension it's ever running using the Game Boy Color driver, even if the ROM is a Classic Game Boy game. The same if I rename it to .bin, it even tries to load as a Mega Drive game.
> If your game was designed for Neo Geo Pocket Color, maybe you can just rename it to .ngc and be loaded in the correct drive.
> Also an extra tip: next releases after the v122 the .exe will be called ares.exe by default (as the development build and the nightly builds just after the v122 already are).
