### ISSUE TITLE
[SG-1000] The Black Onyx Bruce Tomlin+S.Seehorn translation white screen

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#50]
No-Intro Japan dump:
![Black Onyx, The (Japan) 2021-08-11 10-22-57](https://user-images.githubusercontent.com/41223243/128960005-f5a17076-4255-4425-a1bc-ea2ebae6e80c.png)

Translation:
![Black Onyx, The (J) T+En v1 0  Standard Version  Bruce Tomlin+S Seehorn 2021-08-11 10-23-51](https://user-images.githubusercontent.com/41223243/128960015-80a1cc42-0dd8-4335-90d9-5a8c9d0b0ec7.png)

Both Standard and Enhanced versions have the same issue.

**Comment by invertego** [comment]
The patched roms are > 32 KiB in size, which ares currently doesn't support. Some published games were this large, so this really ought to be supported.

**Comment by meowthed** [comment]
closed as per commit https://github.com/higan-emu/ares/commit/ad51e37222d6a393415ace94446c212095b61a0e.
