### ISSUE TITLE
[32x] It feels to me that Sega 32x have 3d rendering core

### ISSUE THREAD

**Issue by WhiteMagicRaven** [ares-emulator/ares#552]
If so its is true?
Can it be in distant future , in theory, upscale 3d like bsnes do it for mode 7 ?

**Comment by LukeUsher** [comment]
This isn't really feasable, the Sega 32X has *no* 3D hardware; it just provides a 2D framebuffer and some extra processors; everything is software rendered and there's no 3D to intercept/upscale.

**Comment by Shideravan** [comment]
That's right. But you can at least use different shader options in ares which can improve your visual experience.
This issue can be safely closed 😊

**Comment by WhiteMagicRaven** [comment]
Well
the games like
Metal Head
and
Virtua Racing Deluxe
the cartridges with this games comes with additional 3d chip on own cartridge?

by reading wikipedia i get confused here
https://en.wikipedia.org/wiki/32X#Development
https://en.wikipedia.org/wiki/Sega_Genesis#Sega_Virtua_Processor
https://en.wikipedia.org/wiki/Sega_Genesis#Sega_32X

it tells that it has limited 3d capabilities

**Comment by LukeUsher** [comment]
> Well the games like Metal Head and Virtua Racing Deluxe the cartridges with this games comes with additional 3d chip on own cartridge?
> 
> by reading wikipedia i get confused here https://en.wikipedia.org/wiki/32X#Development https://en.wikipedia.org/wiki/Sega_Genesis#Sega_Virtua_Processor https://en.wikipedia.org/wiki/Sega_Genesis#Sega_32X
> 
> it tells that it has limited 3d capabilities

all the 3d in these games is done in software, there is no 3D hardware in the 32X, or in these cartridges, it's not much more than just two processors, a framebuffer and a PWM audio channel.

**Comment by WhiteMagicRaven** [comment]
Okay, thank you very much, now everything can be closed.
I am sorry to disturb you with these questions, now i know surely!!!
