### ISSUE TITLE
[GBA] Color pallete: too redish?

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#57]
It seems that the GBA color pallette is too reddish. Principally where it would be pure white color. Take a look at some examples:

![image](https://user-images.githubusercontent.com/12163923/129619562-00cc0473-90eb-48e2-8dc5-28ab12dba9ba.png)
![image](https://user-images.githubusercontent.com/12163923/129619573-da6d3d8c-c715-4f85-8439-b486f97be3c9.png)
![image](https://user-images.githubusercontent.com/12163923/129619635-dadc443b-54ae-41ee-9b02-86c84e97ad8f.png)
![image](https://user-images.githubusercontent.com/12163923/129619703-d7f31a2f-66d8-4122-bc91-39f095434cde.png)
![image](https://user-images.githubusercontent.com/12163923/129619825-02948e03-6a59-40ef-9acc-379142e37a68.png)

This happens in every video driver. 
Tested in the `cb4a79e` version.
SO: Windows 10 x64

**Comment by LukeUsher** [comment]
Did you try disabling color correction in the settings? ares by default attempts to mirror the characteristics of the real LCD, rather than a 'perfect' environment.

**Comment by Shideravan** [comment]
Yes, it seems to be color emulation related. But:

Color emulation off:
![image](https://user-images.githubusercontent.com/12163923/129626113-68113c56-9ebe-4ce0-89be-77af4f96cbbb.png)

Color emulation on:
![image](https://user-images.githubusercontent.com/12163923/129626167-3ec49c76-abd3-48b8-9773-d799cce48651.png)

The menu description says:
"Color emulation: Matches the color to how they look on real hardware".
I have a classic model of the GBA and while I can't say that its screen (that even hasn't a backlight) is the most bright thing in the universe, I'm pretty sure certainly isn't reddish. Are you sure is this the expected behavior?

With backlight:
![image](https://user-images.githubusercontent.com/12163923/129627406-d441894e-159c-4c44-88a6-7b93ffedd6a6.png)

Without backlight (classic model):
![image](https://user-images.githubusercontent.com/12163923/129627457-6907d983-e890-4258-95ac-a70fe7b686ed.png)

**Comment by LukeUsher** [comment]
I just took a look at this, and my GBA SP has a *very* similar red tint; it's pretty close; ares is slightly more pink, but not by as much as your comparison above.

Since the original GBA doesn't have a backlight, I'm leaning towards your unit having an aftermarket screen that changes the display characteristics  

Note that the SP without the light is less red, so the current ares display was likely modeled after an SP with the backlight on, instead of the original AGB; I'll try to match the original AGB better.

**Comment by Shideravan** [comment]
Thanks for the update @LukeUsher 
I think that with the changes in https://github.com/ares-emulator/ares/commit/a6d3a57df93c6f5c9ca6affb2c4c19bf556afe03 I can finally close this issue
