### ISSUE TITLE
[Mega Drive] Sonic 3 & Knuckles just boots into Sonic & Knuckles

### ISSUE THREAD

**Issue by brendynw** [ares-emulator/ares#62]
Any of the Sonic & Knuckles ROMs with other games connected just boot into regular Sonic & Knuckles. Other MD/Genesis emulators do not have this issue, using the same ROMs.

**Comment by meowthed** [comment]
since Sonic & Knuckles is supposed to be attached to the Sonic 1-3 games, I think the ares codebase hasn't implemented support for those dumps yet.

**Comment by Shideravan** [comment]
I think that the ideal behavior is the same as the Super Game Boy. When choosing Sonic and Knuckles cart, users are prompted to choose a cartridge to hook in the S&K cart. If you don't select anything, then run the Sonic & Knuckles without an additional cart as the same Genesis/Mega Drive does.
I'm not sure that these ROMs "S&K+something" physically "exist" in the real world without being a Sonic + Knuckles cart with a Sonic 2 or Sonic 3 hooked in the "S&K upper slot". But I think that would make sense to run these ROMs as a monolith as most emulators do.
Also is valid to note that in the latest ares, if you just run plain "Sonic & Knuckles" (without additional cart inserted) we're getting this wrong screen:
![image](https://user-images.githubusercontent.com/12163923/129815739-1c5500e6-e23b-47c9-9e16-bc874f3795d5.png)

Oh no!
No way!

This only had to show when a Genesis/Mega Drive game other than Sonic 2 or Sonic 3 is inserted, but not the S&K itself (doesn't make any sense to get there recursively).
It's even generating the extra bonuses for... Err... The Sonic & Knuckles ROM itself.
![image](https://user-images.githubusercontent.com/12163923/129816491-22d35500-39aa-4688-a487-5bd55db01da3.png)

**Comment by Shideravan** [comment]
Looking at the manifest, when running the plain "Sonic & Knuckles" from, it's duplicating the Sonic & Knuckles ROM into the slot from the cartridge. It's like starts "Sonic & Knuckles + Sonic & Knuckles"
![image](https://user-images.githubusercontent.com/12163923/129816442-2f9aaaa4-95c6-45e2-9838-2de6f65517b0.png)

**Comment by Shideravan** [comment]
Looking at the manifest, when running the plain "Sonic & Knuckles" from, it's duplicating the Sonic & Knuckles ROM into the slot from the cartridge. It's like starts "Sonic & Knuckles + Sonic & Knuckles"
![image](https://user-images.githubusercontent.com/12163923/129817834-991dab02-cf12-4dc9-aa1f-06b2bd6b9daf.png)


Manifest for the "S&K + Sonic 2"
![image](https://user-images.githubusercontent.com/12163923/129816699-3d5f675e-1a2d-4453-b8fa-8c4b020a0da5.png)

**Comment by LukeUsher** [comment]
Fixed in 7f5be57

**Comment by LukeUsher** [comment]
The super-gameboy style behaviour was not chosen purely because Sonic 2 requires both the Sonic 2 rom, and an additional 'patch' from that is present in Sonic & Knuckles, but not present in said rom dumps; meaning that if the user loaded Sonic 2 as a second rom, it still would not function correctly.

For user-friendliness, conforming to the way existing emulators work is the better option here.
