### ISSUE TITLE
[Request] blargg's NTSC filter support

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#63]
Some old games, in the most different systems, were designed to run on TVs with composite signal input, generating artifacts that in the hands of many skilled developers meant effects that often gave a sensation of volume, different visual effects, and even new colors through some tricks based on the output of the CRT.
Developer Blargg has created an NTSC filter that perfectly simulates this composite cable output.
https://emulation.gametechwiki.com/index.php/NTSC_Filters
It would be nice if we could support these types of filters in Ares.
Take a look at some examples before and after blargg filter:

Little Sansom:
No filter:
![image](https://user-images.githubusercontent.com/12163923/129828438-cd0dc43f-73bf-408a-a17e-89e334cee74e.png)

With blargg filter:
![image](https://user-images.githubusercontent.com/12163923/129828408-cee8da4e-7950-448c-a7e6-dd63312dd7b7.png)
_Personal note: I like how little samsom seems to have angry eyebrows in composite output. This was surely intended by the developer. Unfortunately, this is lost in direct the "modern" output._

Ninja Gaiden II:
No filter:
![image](https://user-images.githubusercontent.com/12163923/129828896-2f7b75a7-5d76-4a34-8989-beb327708c29.png)

With blarrg filter:
![image](https://user-images.githubusercontent.com/12163923/129829029-b01c7135-0ebf-4797-bd5a-137e1c1231c8.png)

Boy and his Blob:
No filter:
![image](https://user-images.githubusercontent.com/12163923/129829143-37d70b78-a739-4ce9-bbe6-f5f7b21979ea.png)

With blargg filter:
![image](https://user-images.githubusercontent.com/12163923/129829202-df9f8168-88ab-49e1-b768-95ede241e517.png)

Also, most of the artifacts created by the NTSC output are dynamic, as you can see in the comparison of the following gif:
![image](https://www.chrismcovell.com/gotRGB/rgb_comp_digital.gif)![image](https://www.chrismcovell.com/gotRGB/rgb_comp_anim.gif)
And something like that is supported by the blarrg's filter

**Comment by Screwtapello** [comment]
blargg's NTSC filter is classic, but it's very highly optimised (difficult to maintain or extend), it really only works for NES-style graphics (256×240 pixels, and assumes details about the NES video encoding hardware), and it can only produce 640×480 output, which means it can't be used on SNES interlaced or hi-res content, never mind the many other wacky video modes ares' emulation cores support.

Instead, you can use the [NTSC shader](https://github.com/hizzlekizzle/quark-shaders/tree/master/NTSC.shader) ported from RetroArch to the format ares already supports. Actually, there's two NTSC shaders - one by Themaister ported from RetroArch, and [another one ported from MAME](https://github.com/hizzlekizzle/quark-shaders/tree/master/NTSC-MAME.shader). Take your pick!

**Comment by LukeUsher** [comment]
Closing for reasons stated above; blargg's NTSC filter is only suitable for NES content, modern shaders are a better alternative.

We can't include the quark-shaders with the download due to licensing restrictions, (GPL vs ISC) but we could add a link to them on the website with installation instructions, it might be worth doing that going forward.
