### ISSUE TITLE
[N64] - General - Immediately loading save state after booting game results in high pitched audio

### ISSUE THREAD

**Issue by HeroponRikiBestest** [ares-emulator/ares#68]
Boot a game (that you already have a savestate on) and load the savestate as soon as the fps counter appears (or just mash load state to be sure you get it) and you will have high pitched audio until you reload the game or the emulator.

Tested with Linux Mint 20, ares 123-dev, pulseaudio driver

**Comment by remutro** [comment]
@HeroponRikiBestest Is this still an issue as of the latest release (currently v131)? I've tried multiple times and haven't been able to reproduce this behavior (although I'm not on Linux Mint). There have been a ton of changes to the N64 core since this was submitted. Can you still reproduce it?

**Comment by HeroponRikiBestest** [comment]
Yep, confirmed still an issue as of right now, v131-dev on Linux Mint 21.1

**Comment by HeroponRikiBestest** [comment]
Tested, seems to be fixed as of latest.
