### ISSUE TITLE
[NES] Let's talk about the missing iNES mappers (and maybe even NES 2.0)

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#72]
Ok, this is one of those issues created to discuss more the topic (and of course, every new info everyone can bring on this topic is welcome). This issue isn't intended to be close soon, as it demands a lot of work to be done.
I made extensive research and tests about different mappers to verify how well they are implemented and I'm compiling everything in a list that I hope to be useful in this journey. Every entry has the iNES mapper number, a link for a list of every official game that uses this mapper (non-official mappers of course will have his entry empty), a link for the NesDev Wiki about the mapper, a name of a known dump that uses the mapper (that was the most difficult task, as I had to research deeply about some very obscure carts and, of course, I also tested every one of them manually in the latest dev version of ares). Note that for a very few of them, I didn't have a proper dump to test - the ones which I haven't the proper dump are marked as red in the "example" column.

* https://docs.google.com/spreadsheets/d/1GIdY2rA4FcPHNfpZ9Y5DDcy0NjYQL9F_2fdPLWAUldg/edit?usp=sharing

About the dumps I used to test, I'm also providing a log of them being used in Mesen: [roms_used_for_mappers_testing.txt](https://github.com/higan-emu/ares/files/7024819/roms_used_for_mappers_testing.txt)
I have also made the same tests on Mesen for comparison as it is the most accurate NES emulator at the moment. You can also take a look at the Mesen source code, as most of the iNES mappers are very well documented too: https://github.com/SourMesen/Mesen
I tried to use common names for the dumps used as examples. Also, some of them are PD made by homebrew projects. Eg:
 * https://action53.itch.io/
 * http://rainwarrior.ca/projects/nes/2a03puritans.html
 * https://www.qmtpro.com/~nes/drip/
 
_Note: these are links to the creators' webpage where they share their own work. Just please be warned that we can't share links in any place about copyrighted material without owner permission (this is always a good reminder). But of course, you can always dump your obscure carts at home and help with the tests. Just be assured you're using a proper dump.
Those PD also have somehow made in physical version too, that's why they uses valid mappers._

There's also very useful information about the mappers in no$nes documentation: https://problemkaputt.de/everynes.htm
If you want access to help to collaborate in this spreadsheet or more information about the dumps used for tests, you can send me a PM. 
Every bit of help is welcome, as we can see, it may take some work (and the mappers must be implemented mostly one by one).
After more iNES mappers are supported in ares, I surely will be glad to reunite all the information possible about the NES 2.0 too.
The idea, of course, is to update the list frequently as more mappers start being supported or more information is gathered.

**Comment by Shideravan** [comment]
I added a new column called "**Ares/Higan behavior with the example dump**" which I better describe the mapper issues in **ares**/**higan**, as it says when tested with the software listed in "examples".

**Comment by AbreuEfechou** [comment]
I think that maybe these "graphics corrupted" games are in fact related CHR Rom bankswitching as described [here](https://wiki.nesdev.com/w/index.php/CHR_ROM_vs._CHR_RAM)

**Comment by remutro** [comment]
Support for iNes 2.0 headers was added to ares in v130

**Comment by LukeUsher** [comment]
Most of the mappers discussed here plus ines 2.0 are both implemented, closing
