### ISSUE TITLE
[MD] NBA Jam (U): Black screen after the Iguana's logo

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#75]
Version: d50e9d2
Windows 10 x64

**Comment by birdybro** [comment]
This is one of the weird few EEPROM games.

Here's some resources on EEPROM games for reference:

EkeEke's eeprom guide. 
http://krikzz.com/pub/support/everdrive-md/v2/gen_eeprom.pdf

NBA Jam specifically:  
![image](https://user-images.githubusercontent.com/16388068/130332217-d0ce2dc4-aa10-47ce-9845-bb7c74092274.png)

Genesis Plus GX's source code for this mapper:
https://github.com/ekeeke/Genesis-Plus-GX/blob/c43cac0cdc881cc119fa030a7b98989b847318af/core/cart_hw/eeprom_i2c.c#L722

Hopefully this will point someone in the right direction.

**Comment by Shideravan** [comment]
It's working in the latest ares version
![image](https://user-images.githubusercontent.com/12163923/192731742-f5b9b7a4-253b-49cd-8026-1ead966d4a00.png)
