### ISSUE TITLE
[GBC] Gex: Enter the Gecko - Freezes after "Crave Entertainment" logo

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#81]
Freezes after this logo:
![image](https://user-images.githubusercontent.com/12163923/130353584-da570290-f401-4fdc-91a1-d205c97027d8.png)

Version tested: cb4a79e
Windows 10 x64

**Comment by invertego** [comment]
The game seems to require that you press the B button to advance. Yes, really, the B button.

**Comment by Shideravan** [comment]
Sorry, false positive.
