### ISSUE TITLE
[PCE] Second controller incorrectly duplicating first port configuration

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#85]
Ares doesn't have second controller support for PCE games yet. Or that's what we expected.
In fact, the second controller is incorrectly being mapped with the same buttons from Controller 1 port.
That causes games such as Bomberman '93 to enter directly to 2 player match rather than the main menu, as when you press "run" it's in fact pressing the run button in both player 1 and 2 controllers.
https://youtu.be/GAJoTl910hY

I'm posting this issue here, so I don't forget it, but I can take a look at this issue later, after [this PR](https://github.com/higan-emu/ares/pull/44) which also make changes in controller mode files is merged (to avoid inconsistencies in my local files). There's is even a skeleton for multiplayer support for PC Engine (using multi-tap).

**Comment by LukeUsher** [comment]
It's worth noting that the PC-Engine console only has a single controller port, two or more controllers require a multitap.

The multi-tap is not yet emulated by ares, so just hooking up the UI to support it simply isn't enough.

There is definitely an issue with input, but it is not related directly to a 'second' controller; it is currently impossible to hook up a second controller to the PC-Engine core.

It's likely the cause of this issue is that Bomberman believes a multi-tap is connected, when it is not.

**Comment by LukeUsher** [comment]
Update: Bomberman '93 Special Version is a special release that *does not support* single player, it was created for a specific event and never had a commercial release, it does not have the main menu either.

Can you please re-test with the standard version of Bomberman '93 or Bomberman '94?

**Comment by Shideravan** [comment]
Bomberman '94
https://youtu.be/dcAwQoIpPQQ

**Comment by LukeUsher** [comment]
Thanks, will investigate

**Comment by Shideravan** [comment]
> Thanks, will investigate

I tested in both MAME and Mednafen, but the same issue happens there too (in both Bomberman '93 and '94) when multitap is off.
Other 2 players games such as Street Fighter II shows VS. Battle turned off in ares (as it's doesn't have multitap support yet).
![image](https://user-images.githubusercontent.com/12163923/130487214-2d3084f1-b632-4ba5-941c-b037290f80c3.png)

It's surely weird if this happens in the PCE console too (and even weirder if you consider that the console itself just has one controller port by default). But after some tests, I'm inclined to accept that this strange behavior happens in the console itself too.
It's probably a false positive

**Comment by Shideravan** [comment]
I closed it for now, but the issue can be reopened if someone has any evidence that this behavior doesn't happen in the console itself

**Comment by LukeUsher** [comment]
@Shideravan hope I’m not being too annoying here but can you please test bomberman 94? I own that game for my pc-engine and can test this one on real hardware.

**Comment by LukeUsher** [comment]
I can confirm this is how games behave on real hardware; see attached video for Bomberman '94.

https://user-images.githubusercontent.com/740003/130518639-8eec4032-9eb3-4a7f-9ecf-58532ab1c5df.mov
