### ISSUE TITLE
Deadzone on n64 is too large.

### ISSUE THREAD

**Issue by numbypad** [ares-emulator/ares#86]
Ares seems to perfectly emulate the analog gate of the n64 controller no matter what controller is used, I've tested multiple controllers with the n64 controller test rom and the gate was almost perfect every time, this is an amazing feature for someone like myself who is wanting the most console accurate experience. however, it seems the deadzone is a bit too large, when tested with all of the controllers, including an N64 through raphnet directinput adapter, the deadzone was much larger than console. I suppose this isn't exactly a big deal, but would be much appreciated if fixed as if it were corrected with this emulators lack of input lag it would make it one of the best ways to speedrun n64 on emulator.

**Comment by remutro** [comment]
Are there "known" values that are closer to actual hardware (or maybe a test app)? Or perhaps another emulator that seems to get this closer to hardware? Having actual values would help, otherwise it ends up being based on what someone feels is correct.

**Comment by numbypad** [comment]
using the N64 controller test rom on actual hardware using oem controllers, the deadzone is practically none existent. with even the slightest touch triggering a value of 1. Project64 seems to have the correct deadzone when using an oem controller through a raphnet adapter paired with the pj64 raphnet direct input plugin. sadly, in almost every emulator I have tried, besides ares, the controller test rom doesn't work properly, I can say when setting the value to 0.0 in Retroarch it is very similar if not exact to both project64 using the DirectInput plugin or real hardware.

**Comment by numbypad** [comment]
I should also mention I tested this with multiple oem n64 controllers all of which had a 10/10 stick.

**Comment by remutro** [comment]
After having some converations, we should really expose the deadzone threshold to end users so they can set this themselves. It's never going to feel "right" using different controllers. Some examples of emulators that do this are Cemu, rpcs3, & Yuzu. If we did the same thing, then users could configure it until it felt "right" to them.

**Comment by numbypad** [comment]
that would be great!

**Comment by kev4cards** [comment]
I have been working with on this issue with another emulator developer and Sanni, the creator of the controller test ROM. Sanni provided crude (according to him) angle measurements for -1 to 1 movement along with full-axis movement. The angles are 3.46° and 64.6°, respectively. This creates a ~5.36% deadzone. Multiplying this by the max axis value of 85 implies a 4.55 "movement unit" deadzone. Lastly and probably more importantly, the deadzone needs to be in the shape of a square to be in line with the N64's programming manual's controller specifications.

**Comment by kev4cards** [comment]
@numbypad I have opened a PR to address this issue. Feel free to build yourself or test when a GitHub build becomes available. This should give you a better N64-controller-like experience on a non-N64 controller.
