### ISSUE TITLE
[UI] Load button doesn't work if emulator menu is clicked in initial loading

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#90]
Title.

**Comment by remutro** [comment]
What platform was this on as it could very well be platform specific? I can't seem to reproduce it on Windows at least. Or perhaps I'm not fast enough?

**Comment by Shideravan** [comment]
I cannot reproduce it too in Windows 10 x64. Even in Sega CD + 32X which is the slowest system to load. After the game properly loads, the "load" button returns to work as expected and this is the closest I can get to this issue. Other systems load too fast to even be reproducible.
https://youtu.be/IqMEb8t0U6w

**Comment by meowthed** [comment]
To reproduce, launch ares, and click anywhere in the drop-down menu just before the status bar reads "Unloaded".

**Comment by jbo-85** [comment]
This piece of code is responsible for the hanging Load menu-button, it doesn't work when Application::modal() returns something non-zero

```diff --git a/desktop-ui/program/program.cpp b/desktop-ui/program/program.cpp
index db695dbe6..013206e20 100644
--- a/desktop-ui/program/program.cpp
+++ b/desktop-ui/program/program.cpp
@@ -30,10 +30,12 @@ auto Program::create() -> void {
 }

 auto Program::main() -> void {
+  puts("Program Main 1");
   if(Application::modal()) {
     ruby::audio.clear();
     return;
   }
+  puts("Program Main 2");

   updateMessage();
   inputManager.poll();
```

The menu is modal because of this snippet:
```
hiro/windows/window.cpp:
  if(msg == WM_ENTERMENULOOP || msg == WM_ENTERSIZEMOVE) {
    modalIncrement();
    return false;
  }

  if(msg == WM_EXITMENULOOP || msg == WM_EXITSIZEMOVE) {
    modalDecrement();
    return false;
  }
```

I could reduce the hangs a bit after calling presentation.loadEmulators() earlier:
```
diff --git a/desktop-ui/desktop-ui.cpp b/desktop-ui/desktop-ui.cpp
index 2deb58ad2..56661b2e8 100644
--- a/desktop-ui/desktop-ui.cpp
+++ b/desktop-ui/desktop-ui.cpp
@@ -45,11 +45,11 @@ auto nall::main(Arguments arguments) -> void {
   Emulator::construct();
   settings.load();
   Instances::presentation.construct();
+  presentation.loadEmulators();
   Instances::settingsWindow.construct();
   Instances::toolsWindow.construct();

   program.create();
-  presentation.loadEmulators();
   Application::onMain({&Program::main, &program});
   Application::run();
```

**Comment by jbo-85** [comment]
The changes to those files were introduced in those commits:
https://github.com/higan-emu/higan/commit/9a6ae6dacb12d2ae089b6249cf4462993eca0790
```
20180809: // inital modal changes without ruby::audio.clear();
Changelog
The Windows port can now run the emulation while navigating menus,
moving windows, and resizing windows. The main window also doesn't try
so hard to constantly clear itself. This may leave a bit of unwelcome
residue behind in some video drivers during resize, but under most
drivers, it lets you resize without a huge amount of flickering.

On all platforms, I now also run the emulation during MessageWindow
modal events, where I didn't before.

I'm thinking we should probably mute the audio during modal periods,
since it can generate a good deal of distortion.
```
https://github.com/higan-emu/higan/commit/bdf2c4053f61c5bf34bb917f2b9c81b104905b0c
```
v107.22: // ruby::audio.clear(); added
Changelog
byuu v1:
* Windows: fix an occasional crash when unloading games
* Windows: fix beeping sound when assigning inputs and hotkeys
```

**Comment by jbo-85** [comment]
the modal code from my previous comments isn't really a problem here, even after removing that it still hangs sometimes
Apparently it all started in commit https://github.com/higan-emu/ares/commit/4af59c63f1e0d2e9fdf89770f3fd726d463770e2 which is absolutely gigantic

**Comment by LukeUsher** [comment]
This should be resolved in the latest release: we now delay the window showing until after the emulator cores have finished loading.
