### ISSUE TITLE
[ColecoVision] Support for .rom format

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#91]
AFAIK the only games that are distributed in that format are homebrews from Collectorvision Games.

**Comment by LukeUsher** [comment]
Can you provide more details? what makes .rom different from .bin/,col? Is it a different format entirely?

I'd expect it's just a different filename; renaming them to a more sane extension should be enough.

**Comment by Kawa-oneechan** [comment]
I'm gonna be silly on purpose: how would you tell a ColecoVision .bin apart from a Genedrive .bin?

**Comment by Shideravan** [comment]
> I'm gonna be silly on purpose: how would you tell a ColecoVision .bin apart from a Genedrive .bin?

Structurally none. But ares hadn't support for .bin also. I gave support for both in this PR. eg.: This is Dacman which is usually distributed in .rom format
![image](https://user-images.githubusercontent.com/12163923/130492748-b8e14d1f-4df4-462a-a74a-2d38789dc3d3.png)
![image](https://user-images.githubusercontent.com/12163923/130492871-838373cb-6684-4f71-ac71-a2da19ba23dd.png)

**Comment by FitzRoyX** [comment]
Generic extensions aren't a good idea and if a game came this way, it should be changed. The same game can be ported to different systems. Not only is "Pac-Man (U).rom" not identifiable on its own, two versions of the same name cannot coexist in the same directory. This also means sram files generated from these roms would collide if they got moved to a shared directory. That is fixable under current methods with double extensions, but not if games are distributed as bin and rom.

**Comment by Shideravan** [comment]
> Generic extensions aren't a good idea and if a game came this way, it should be changed. The same game can be ported to different systems. Not only is "Pac-Man (U).rom" not identifiable on its own, two versions of the same name cannot coexist in the same directory. This also means sram files generated from these roms would collide if they got moved to a shared directory. That is fixable under current methods with double extensions, but not if games are distributed as bin and rom.

But PD for ColecoVision is historically distributed as these extensions. The main purpose of ares is to be as easy to use as possible. it makes no sense to require the user to know that he MUST change a PD extension before running it in Ares when all other emulators have support for it. Sorry, but sometimes I feel like you complain just to complain.

**Comment by Shideravan** [comment]
> Generic extensions aren't a good idea and if a game came this way, it should be changed. The same game can be ported to different systems. Not only is "Pac-Man (U).rom" not identifiable on its own, two versions of the same name cannot coexist in the same directory. This also means sram files generated from these roms would collide if they got moved to a shared directory. That is fixable under current methods with double extensions, but not if games are distributed as bin and rom.

Also, the name isn't Pac-Man (U).rom. It's Dacman(PD). But this isn't the only homebrew game distributed this way. You can just google for "Colecovision homebrew games" and see by yourself that historically every PD game for Colecovision is distributed as one of these extensions. Please, at least do a google search before complaining about anything.

**Comment by FitzRoyX** [comment]
> when all other emulators have support for it.

That's why bad practices persist, though. Emulators fighting to load the most rawmz instead of coming together and enforcing sensible standards. I see this as no different from SMC or interleaved roms ballooning in the heyday of SNES emulation. Colecovision should clearly have a .col or .colv extension.

It's also worth noting that Near was aware of all this and hated generic extensions. That's why BIN on genesis isn't supported.

> It's Dacman(PD).

It... doesn't matter. And stop upvoting yourself minutes after you post with burner accounts, it's annoying.

**Comment by Shideravan** [comment]
What?

**Comment by AbreuEfechou** [comment]
> > when all other emulators have support for it.
> 
> That's why bad practices persist, though. Emulators fighting to load the most rawmz instead of coming together and enforcing sensible standards. I see this as no different from SMC or interleaved roms ballooning in the heyday of SNES emulation. Colecovision should clearly have a .col or .colv extension.
> 
> It's also worth noting that Near was aware of all this and hated generic extensions. That's why BIN on genesis isn't supported.
> 
> > It's Dacman(PD).
> 
> It... doesn't matter. And stop upvoting yourself minutes after you post with burner accounts, it's annoying.

what are you talking about Mr. "my nickname is a supremacist dog whistle as a reference for Charles Darwin ship captain"?
https://en.wikipedia.org/wiki/Robert_FitzRoy

**Comment by AbreuEfechou** [comment]
If you guys have personal problems keep it on PM.

**Comment by Shideravan** [comment]
> If you guys have personal problems keep it on PM.

I'm not a guy, I'm a capybara.

**Comment by meowthed** [comment]
yeah I don't think this is a good idea in the long run, probably best to just rename those roms instead in it's proper format. While I think .rom should be fine, .bin kinda conflicts with Mega Drive.
