### ISSUE TITLE
[WonderSwan] Slow Audio, despite 60fps

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#93]
A good observation would be Golden Axe, compare https://www.youtube.com/watch?v=OasD9rzXESM with Ares emulation.

**Comment by LukeUsher** [comment]
Make sure that you don't have video synchronization/vsync enabled: WonderSwan systems should run at 75hz, not 60!

**Comment by Kawa-oneechan** [comment]
I saw this issue listed and I thought "betcha the WS doesn't run at 60". Read some other issues, got to this one and _hey presto!_

**Comment by Shideravan** [comment]
No issues were found when running at proper 75Hz
https://youtu.be/MRfquVG1LDs

**Comment by arnoldsecret** [comment]
I think my confusion came to be thanks to the OpenGL driver being stuck running at 60fps when it should be 75. DX9.0 driver hits 75 though.

**Comment by meowthed** [comment]
So the culprit is audio sync being enabled as default.
